server:
  port: 8083
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lian_test
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.example.demo
configuration:
  status: warn
  appenders:
    Console:
    name: CONSOLE
    target: SYSTEM_OUT
    ThresholdFilter:
      leve: ${sys:log.level.console}
      onMatch: ACCEPT
      onMismatch: DENY
    PatternLayout:
      pattern: "%d{yyyy-MM-dd}:"