package com.example.demo.bean;

import java.util.ArrayList;
import java.util.List;

public class AccesslogExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ACCESSLOG
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ACCESSLOG
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ACCESSLOG
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCESSLOG
     *
     * @mbg.generated
     */
    public AccesslogExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCESSLOG
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCESSLOG
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCESSLOG
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCESSLOG
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCESSLOG
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCESSLOG
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCESSLOG
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCESSLOG
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCESSLOG
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCESSLOG
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ACCESSLOG
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("userid is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("userid is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(String value) {
            addCriterion("userid =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(String value) {
            addCriterion("userid <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(String value) {
            addCriterion("userid >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(String value) {
            addCriterion("userid >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(String value) {
            addCriterion("userid <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(String value) {
            addCriterion("userid <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLike(String value) {
            addCriterion("userid like", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotLike(String value) {
            addCriterion("userid not like", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<String> values) {
            addCriterion("userid in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<String> values) {
            addCriterion("userid not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(String value1, String value2) {
            addCriterion("userid between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(String value1, String value2) {
            addCriterion("userid not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andAccessurlIsNull() {
            addCriterion("accessurl is null");
            return (Criteria) this;
        }

        public Criteria andAccessurlIsNotNull() {
            addCriterion("accessurl is not null");
            return (Criteria) this;
        }

        public Criteria andAccessurlEqualTo(String value) {
            addCriterion("accessurl =", value, "accessurl");
            return (Criteria) this;
        }

        public Criteria andAccessurlNotEqualTo(String value) {
            addCriterion("accessurl <>", value, "accessurl");
            return (Criteria) this;
        }

        public Criteria andAccessurlGreaterThan(String value) {
            addCriterion("accessurl >", value, "accessurl");
            return (Criteria) this;
        }

        public Criteria andAccessurlGreaterThanOrEqualTo(String value) {
            addCriterion("accessurl >=", value, "accessurl");
            return (Criteria) this;
        }

        public Criteria andAccessurlLessThan(String value) {
            addCriterion("accessurl <", value, "accessurl");
            return (Criteria) this;
        }

        public Criteria andAccessurlLessThanOrEqualTo(String value) {
            addCriterion("accessurl <=", value, "accessurl");
            return (Criteria) this;
        }

        public Criteria andAccessurlLike(String value) {
            addCriterion("accessurl like", value, "accessurl");
            return (Criteria) this;
        }

        public Criteria andAccessurlNotLike(String value) {
            addCriterion("accessurl not like", value, "accessurl");
            return (Criteria) this;
        }

        public Criteria andAccessurlIn(List<String> values) {
            addCriterion("accessurl in", values, "accessurl");
            return (Criteria) this;
        }

        public Criteria andAccessurlNotIn(List<String> values) {
            addCriterion("accessurl not in", values, "accessurl");
            return (Criteria) this;
        }

        public Criteria andAccessurlBetween(String value1, String value2) {
            addCriterion("accessurl between", value1, value2, "accessurl");
            return (Criteria) this;
        }

        public Criteria andAccessurlNotBetween(String value1, String value2) {
            addCriterion("accessurl not between", value1, value2, "accessurl");
            return (Criteria) this;
        }

        public Criteria andAccessnameIsNull() {
            addCriterion("accessname is null");
            return (Criteria) this;
        }

        public Criteria andAccessnameIsNotNull() {
            addCriterion("accessname is not null");
            return (Criteria) this;
        }

        public Criteria andAccessnameEqualTo(String value) {
            addCriterion("accessname =", value, "accessname");
            return (Criteria) this;
        }

        public Criteria andAccessnameNotEqualTo(String value) {
            addCriterion("accessname <>", value, "accessname");
            return (Criteria) this;
        }

        public Criteria andAccessnameGreaterThan(String value) {
            addCriterion("accessname >", value, "accessname");
            return (Criteria) this;
        }

        public Criteria andAccessnameGreaterThanOrEqualTo(String value) {
            addCriterion("accessname >=", value, "accessname");
            return (Criteria) this;
        }

        public Criteria andAccessnameLessThan(String value) {
            addCriterion("accessname <", value, "accessname");
            return (Criteria) this;
        }

        public Criteria andAccessnameLessThanOrEqualTo(String value) {
            addCriterion("accessname <=", value, "accessname");
            return (Criteria) this;
        }

        public Criteria andAccessnameLike(String value) {
            addCriterion("accessname like", value, "accessname");
            return (Criteria) this;
        }

        public Criteria andAccessnameNotLike(String value) {
            addCriterion("accessname not like", value, "accessname");
            return (Criteria) this;
        }

        public Criteria andAccessnameIn(List<String> values) {
            addCriterion("accessname in", values, "accessname");
            return (Criteria) this;
        }

        public Criteria andAccessnameNotIn(List<String> values) {
            addCriterion("accessname not in", values, "accessname");
            return (Criteria) this;
        }

        public Criteria andAccessnameBetween(String value1, String value2) {
            addCriterion("accessname between", value1, value2, "accessname");
            return (Criteria) this;
        }

        public Criteria andAccessnameNotBetween(String value1, String value2) {
            addCriterion("accessname not between", value1, value2, "accessname");
            return (Criteria) this;
        }

        public Criteria andAccessnumIsNull() {
            addCriterion("accessnum is null");
            return (Criteria) this;
        }

        public Criteria andAccessnumIsNotNull() {
            addCriterion("accessnum is not null");
            return (Criteria) this;
        }

        public Criteria andAccessnumEqualTo(String value) {
            addCriterion("accessnum =", value, "accessnum");
            return (Criteria) this;
        }

        public Criteria andAccessnumNotEqualTo(String value) {
            addCriterion("accessnum <>", value, "accessnum");
            return (Criteria) this;
        }

        public Criteria andAccessnumGreaterThan(String value) {
            addCriterion("accessnum >", value, "accessnum");
            return (Criteria) this;
        }

        public Criteria andAccessnumGreaterThanOrEqualTo(String value) {
            addCriterion("accessnum >=", value, "accessnum");
            return (Criteria) this;
        }

        public Criteria andAccessnumLessThan(String value) {
            addCriterion("accessnum <", value, "accessnum");
            return (Criteria) this;
        }

        public Criteria andAccessnumLessThanOrEqualTo(String value) {
            addCriterion("accessnum <=", value, "accessnum");
            return (Criteria) this;
        }

        public Criteria andAccessnumLike(String value) {
            addCriterion("accessnum like", value, "accessnum");
            return (Criteria) this;
        }

        public Criteria andAccessnumNotLike(String value) {
            addCriterion("accessnum not like", value, "accessnum");
            return (Criteria) this;
        }

        public Criteria andAccessnumIn(List<String> values) {
            addCriterion("accessnum in", values, "accessnum");
            return (Criteria) this;
        }

        public Criteria andAccessnumNotIn(List<String> values) {
            addCriterion("accessnum not in", values, "accessnum");
            return (Criteria) this;
        }

        public Criteria andAccessnumBetween(String value1, String value2) {
            addCriterion("accessnum between", value1, value2, "accessnum");
            return (Criteria) this;
        }

        public Criteria andAccessnumNotBetween(String value1, String value2) {
            addCriterion("accessnum not between", value1, value2, "accessnum");
            return (Criteria) this;
        }

        public Criteria andAccesstimeIsNull() {
            addCriterion("accesstime is null");
            return (Criteria) this;
        }

        public Criteria andAccesstimeIsNotNull() {
            addCriterion("accesstime is not null");
            return (Criteria) this;
        }

        public Criteria andAccesstimeEqualTo(String value) {
            addCriterion("accesstime =", value, "accesstime");
            return (Criteria) this;
        }

        public Criteria andAccesstimeNotEqualTo(String value) {
            addCriterion("accesstime <>", value, "accesstime");
            return (Criteria) this;
        }

        public Criteria andAccesstimeGreaterThan(String value) {
            addCriterion("accesstime >", value, "accesstime");
            return (Criteria) this;
        }

        public Criteria andAccesstimeGreaterThanOrEqualTo(String value) {
            addCriterion("accesstime >=", value, "accesstime");
            return (Criteria) this;
        }

        public Criteria andAccesstimeLessThan(String value) {
            addCriterion("accesstime <", value, "accesstime");
            return (Criteria) this;
        }

        public Criteria andAccesstimeLessThanOrEqualTo(String value) {
            addCriterion("accesstime <=", value, "accesstime");
            return (Criteria) this;
        }

        public Criteria andAccesstimeLike(String value) {
            addCriterion("accesstime like", value, "accesstime");
            return (Criteria) this;
        }

        public Criteria andAccesstimeNotLike(String value) {
            addCriterion("accesstime not like", value, "accesstime");
            return (Criteria) this;
        }

        public Criteria andAccesstimeIn(List<String> values) {
            addCriterion("accesstime in", values, "accesstime");
            return (Criteria) this;
        }

        public Criteria andAccesstimeNotIn(List<String> values) {
            addCriterion("accesstime not in", values, "accesstime");
            return (Criteria) this;
        }

        public Criteria andAccesstimeBetween(String value1, String value2) {
            addCriterion("accesstime between", value1, value2, "accesstime");
            return (Criteria) this;
        }

        public Criteria andAccesstimeNotBetween(String value1, String value2) {
            addCriterion("accesstime not between", value1, value2, "accesstime");
            return (Criteria) this;
        }

        public Criteria andXitongIsNull() {
            addCriterion("xitong is null");
            return (Criteria) this;
        }

        public Criteria andXitongIsNotNull() {
            addCriterion("xitong is not null");
            return (Criteria) this;
        }

        public Criteria andXitongEqualTo(String value) {
            addCriterion("xitong =", value, "xitong");
            return (Criteria) this;
        }

        public Criteria andXitongNotEqualTo(String value) {
            addCriterion("xitong <>", value, "xitong");
            return (Criteria) this;
        }

        public Criteria andXitongGreaterThan(String value) {
            addCriterion("xitong >", value, "xitong");
            return (Criteria) this;
        }

        public Criteria andXitongGreaterThanOrEqualTo(String value) {
            addCriterion("xitong >=", value, "xitong");
            return (Criteria) this;
        }

        public Criteria andXitongLessThan(String value) {
            addCriterion("xitong <", value, "xitong");
            return (Criteria) this;
        }

        public Criteria andXitongLessThanOrEqualTo(String value) {
            addCriterion("xitong <=", value, "xitong");
            return (Criteria) this;
        }

        public Criteria andXitongLike(String value) {
            addCriterion("xitong like", value, "xitong");
            return (Criteria) this;
        }

        public Criteria andXitongNotLike(String value) {
            addCriterion("xitong not like", value, "xitong");
            return (Criteria) this;
        }

        public Criteria andXitongIn(List<String> values) {
            addCriterion("xitong in", values, "xitong");
            return (Criteria) this;
        }

        public Criteria andXitongNotIn(List<String> values) {
            addCriterion("xitong not in", values, "xitong");
            return (Criteria) this;
        }

        public Criteria andXitongBetween(String value1, String value2) {
            addCriterion("xitong between", value1, value2, "xitong");
            return (Criteria) this;
        }

        public Criteria andXitongNotBetween(String value1, String value2) {
            addCriterion("xitong not between", value1, value2, "xitong");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ACCESSLOG
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ACCESSLOG
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}