package com.example.demo.bean;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table fund_lp
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class FundLp {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_lp.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * Database Column Remarks:
     *   投资状态1初步沟通，2资料评审，3承诺投资，4回访确认期，5已投资，6放弃投资
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_lp.investment_status
     *
     * @mbg.generated
     */
    private String investmentStatus;

    /**
     * Database Column Remarks:
     *   服务人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_lp.lp_name
     *
     * @mbg.generated
     */
    private String lpName;

    /**
     * Database Column Remarks:
     *   募资记录
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_lp.investment_record
     *
     * @mbg.generated
     */
    private String investmentRecord;

    /**
     * Database Column Remarks:
     *   基金id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_lp.fund_id
     *
     * @mbg.generated
     */
    private String fundId;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_lp.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_lp.update_date
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     * Database Column Remarks:
     *   删除标志
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_lp.deteledstatus
     *
     * @mbg.generated
     */
    private Integer deteledstatus;

    /**
     * Database Column Remarks:
     *   拟投金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_lp.proposed_amount
     *
     * @mbg.generated
     */
    private String proposedAmount;

    /**
     * Database Column Remarks:
     *   对应的lp
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_lp.lp_id
     *
     * @mbg.generated
     */
    private String lpId;

    /**
     * Database Column Remarks:
     *   lp名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_lp.lp_guestname
     *
     * @mbg.generated
     */
    private String lpGuestname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_lp.id
     *
     * @return the value of fund_lp.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_lp.id
     *
     * @param id the value for fund_lp.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_lp.investment_status
     *
     * @return the value of fund_lp.investment_status
     *
     * @mbg.generated
     */
    public String getInvestmentStatus() {
        return investmentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_lp.investment_status
     *
     * @param investmentStatus the value for fund_lp.investment_status
     *
     * @mbg.generated
     */
    public void setInvestmentStatus(String investmentStatus) {
        this.investmentStatus = investmentStatus == null ? null : investmentStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_lp.lp_name
     *
     * @return the value of fund_lp.lp_name
     *
     * @mbg.generated
     */
    public String getLpName() {
        return lpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_lp.lp_name
     *
     * @param lpName the value for fund_lp.lp_name
     *
     * @mbg.generated
     */
    public void setLpName(String lpName) {
        this.lpName = lpName == null ? null : lpName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_lp.investment_record
     *
     * @return the value of fund_lp.investment_record
     *
     * @mbg.generated
     */
    public String getInvestmentRecord() {
        return investmentRecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_lp.investment_record
     *
     * @param investmentRecord the value for fund_lp.investment_record
     *
     * @mbg.generated
     */
    public void setInvestmentRecord(String investmentRecord) {
        this.investmentRecord = investmentRecord == null ? null : investmentRecord.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_lp.fund_id
     *
     * @return the value of fund_lp.fund_id
     *
     * @mbg.generated
     */
    public String getFundId() {
        return fundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_lp.fund_id
     *
     * @param fundId the value for fund_lp.fund_id
     *
     * @mbg.generated
     */
    public void setFundId(String fundId) {
        this.fundId = fundId == null ? null : fundId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_lp.create_date
     *
     * @return the value of fund_lp.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_lp.create_date
     *
     * @param createDate the value for fund_lp.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_lp.update_date
     *
     * @return the value of fund_lp.update_date
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_lp.update_date
     *
     * @param updateDate the value for fund_lp.update_date
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_lp.deteledstatus
     *
     * @return the value of fund_lp.deteledstatus
     *
     * @mbg.generated
     */
    public Integer getDeteledstatus() {
        return deteledstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_lp.deteledstatus
     *
     * @param deteledstatus the value for fund_lp.deteledstatus
     *
     * @mbg.generated
     */
    public void setDeteledstatus(Integer deteledstatus) {
        this.deteledstatus = deteledstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_lp.proposed_amount
     *
     * @return the value of fund_lp.proposed_amount
     *
     * @mbg.generated
     */
    public String getProposedAmount() {
        return proposedAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_lp.proposed_amount
     *
     * @param proposedAmount the value for fund_lp.proposed_amount
     *
     * @mbg.generated
     */
    public void setProposedAmount(String proposedAmount) {
        this.proposedAmount = proposedAmount == null ? null : proposedAmount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_lp.lp_id
     *
     * @return the value of fund_lp.lp_id
     *
     * @mbg.generated
     */
    public String getLpId() {
        return lpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_lp.lp_id
     *
     * @param lpId the value for fund_lp.lp_id
     *
     * @mbg.generated
     */
    public void setLpId(String lpId) {
        this.lpId = lpId == null ? null : lpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_lp.lp_guestname
     *
     * @return the value of fund_lp.lp_guestname
     *
     * @mbg.generated
     */
    public String getLpGuestname() {
        return lpGuestname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_lp.lp_guestname
     *
     * @param lpGuestname the value for fund_lp.lp_guestname
     *
     * @mbg.generated
     */
    public void setLpGuestname(String lpGuestname) {
        this.lpGuestname = lpGuestname == null ? null : lpGuestname.trim();
    }
}