package com.example.demo.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FundPartnerRelExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fund_partner_rel
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fund_partner_rel
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fund_partner_rel
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_partner_rel
     *
     * @mbg.generated
     */
    public FundPartnerRelExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_partner_rel
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_partner_rel
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_partner_rel
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_partner_rel
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_partner_rel
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_partner_rel
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_partner_rel
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_partner_rel
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_partner_rel
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_partner_rel
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fund_partner_rel
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeIsNull() {
            addCriterion("business_type is null");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeIsNotNull() {
            addCriterion("business_type is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeEqualTo(String value) {
            addCriterion("business_type =", value, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeNotEqualTo(String value) {
            addCriterion("business_type <>", value, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeGreaterThan(String value) {
            addCriterion("business_type >", value, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeGreaterThanOrEqualTo(String value) {
            addCriterion("business_type >=", value, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeLessThan(String value) {
            addCriterion("business_type <", value, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeLessThanOrEqualTo(String value) {
            addCriterion("business_type <=", value, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeLike(String value) {
            addCriterion("business_type like", value, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeNotLike(String value) {
            addCriterion("business_type not like", value, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeIn(List<String> values) {
            addCriterion("business_type in", values, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeNotIn(List<String> values) {
            addCriterion("business_type not in", values, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeBetween(String value1, String value2) {
            addCriterion("business_type between", value1, value2, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeNotBetween(String value1, String value2) {
            addCriterion("business_type not between", value1, value2, "businessType");
            return (Criteria) this;
        }

        public Criteria andFundidIsNull() {
            addCriterion("fundid is null");
            return (Criteria) this;
        }

        public Criteria andFundidIsNotNull() {
            addCriterion("fundid is not null");
            return (Criteria) this;
        }

        public Criteria andFundidEqualTo(String value) {
            addCriterion("fundid =", value, "fundid");
            return (Criteria) this;
        }

        public Criteria andFundidNotEqualTo(String value) {
            addCriterion("fundid <>", value, "fundid");
            return (Criteria) this;
        }

        public Criteria andFundidGreaterThan(String value) {
            addCriterion("fundid >", value, "fundid");
            return (Criteria) this;
        }

        public Criteria andFundidGreaterThanOrEqualTo(String value) {
            addCriterion("fundid >=", value, "fundid");
            return (Criteria) this;
        }

        public Criteria andFundidLessThan(String value) {
            addCriterion("fundid <", value, "fundid");
            return (Criteria) this;
        }

        public Criteria andFundidLessThanOrEqualTo(String value) {
            addCriterion("fundid <=", value, "fundid");
            return (Criteria) this;
        }

        public Criteria andFundidLike(String value) {
            addCriterion("fundid like", value, "fundid");
            return (Criteria) this;
        }

        public Criteria andFundidNotLike(String value) {
            addCriterion("fundid not like", value, "fundid");
            return (Criteria) this;
        }

        public Criteria andFundidIn(List<String> values) {
            addCriterion("fundid in", values, "fundid");
            return (Criteria) this;
        }

        public Criteria andFundidNotIn(List<String> values) {
            addCriterion("fundid not in", values, "fundid");
            return (Criteria) this;
        }

        public Criteria andFundidBetween(String value1, String value2) {
            addCriterion("fundid between", value1, value2, "fundid");
            return (Criteria) this;
        }

        public Criteria andFundidNotBetween(String value1, String value2) {
            addCriterion("fundid not between", value1, value2, "fundid");
            return (Criteria) this;
        }

        public Criteria andFpidIsNull() {
            addCriterion("fpid is null");
            return (Criteria) this;
        }

        public Criteria andFpidIsNotNull() {
            addCriterion("fpid is not null");
            return (Criteria) this;
        }

        public Criteria andFpidEqualTo(String value) {
            addCriterion("fpid =", value, "fpid");
            return (Criteria) this;
        }

        public Criteria andFpidNotEqualTo(String value) {
            addCriterion("fpid <>", value, "fpid");
            return (Criteria) this;
        }

        public Criteria andFpidGreaterThan(String value) {
            addCriterion("fpid >", value, "fpid");
            return (Criteria) this;
        }

        public Criteria andFpidGreaterThanOrEqualTo(String value) {
            addCriterion("fpid >=", value, "fpid");
            return (Criteria) this;
        }

        public Criteria andFpidLessThan(String value) {
            addCriterion("fpid <", value, "fpid");
            return (Criteria) this;
        }

        public Criteria andFpidLessThanOrEqualTo(String value) {
            addCriterion("fpid <=", value, "fpid");
            return (Criteria) this;
        }

        public Criteria andFpidLike(String value) {
            addCriterion("fpid like", value, "fpid");
            return (Criteria) this;
        }

        public Criteria andFpidNotLike(String value) {
            addCriterion("fpid not like", value, "fpid");
            return (Criteria) this;
        }

        public Criteria andFpidIn(List<String> values) {
            addCriterion("fpid in", values, "fpid");
            return (Criteria) this;
        }

        public Criteria andFpidNotIn(List<String> values) {
            addCriterion("fpid not in", values, "fpid");
            return (Criteria) this;
        }

        public Criteria andFpidBetween(String value1, String value2) {
            addCriterion("fpid between", value1, value2, "fpid");
            return (Criteria) this;
        }

        public Criteria andFpidNotBetween(String value1, String value2) {
            addCriterion("fpid not between", value1, value2, "fpid");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createtime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createtime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("createtime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("createtime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("createtime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createtime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("createtime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("createtime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("createtime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("createtime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("createtime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("createtime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andDeteledstatusIsNull() {
            addCriterion("deteledstatus is null");
            return (Criteria) this;
        }

        public Criteria andDeteledstatusIsNotNull() {
            addCriterion("deteledstatus is not null");
            return (Criteria) this;
        }

        public Criteria andDeteledstatusEqualTo(Integer value) {
            addCriterion("deteledstatus =", value, "deteledstatus");
            return (Criteria) this;
        }

        public Criteria andDeteledstatusNotEqualTo(Integer value) {
            addCriterion("deteledstatus <>", value, "deteledstatus");
            return (Criteria) this;
        }

        public Criteria andDeteledstatusGreaterThan(Integer value) {
            addCriterion("deteledstatus >", value, "deteledstatus");
            return (Criteria) this;
        }

        public Criteria andDeteledstatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("deteledstatus >=", value, "deteledstatus");
            return (Criteria) this;
        }

        public Criteria andDeteledstatusLessThan(Integer value) {
            addCriterion("deteledstatus <", value, "deteledstatus");
            return (Criteria) this;
        }

        public Criteria andDeteledstatusLessThanOrEqualTo(Integer value) {
            addCriterion("deteledstatus <=", value, "deteledstatus");
            return (Criteria) this;
        }

        public Criteria andDeteledstatusIn(List<Integer> values) {
            addCriterion("deteledstatus in", values, "deteledstatus");
            return (Criteria) this;
        }

        public Criteria andDeteledstatusNotIn(List<Integer> values) {
            addCriterion("deteledstatus not in", values, "deteledstatus");
            return (Criteria) this;
        }

        public Criteria andDeteledstatusBetween(Integer value1, Integer value2) {
            addCriterion("deteledstatus between", value1, value2, "deteledstatus");
            return (Criteria) this;
        }

        public Criteria andDeteledstatusNotBetween(Integer value1, Integer value2) {
            addCriterion("deteledstatus not between", value1, value2, "deteledstatus");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andSubscribedMoneyIsNull() {
            addCriterion("subscribed_money is null");
            return (Criteria) this;
        }

        public Criteria andSubscribedMoneyIsNotNull() {
            addCriterion("subscribed_money is not null");
            return (Criteria) this;
        }

        public Criteria andSubscribedMoneyEqualTo(String value) {
            addCriterion("subscribed_money =", value, "subscribedMoney");
            return (Criteria) this;
        }

        public Criteria andSubscribedMoneyNotEqualTo(String value) {
            addCriterion("subscribed_money <>", value, "subscribedMoney");
            return (Criteria) this;
        }

        public Criteria andSubscribedMoneyGreaterThan(String value) {
            addCriterion("subscribed_money >", value, "subscribedMoney");
            return (Criteria) this;
        }

        public Criteria andSubscribedMoneyGreaterThanOrEqualTo(String value) {
            addCriterion("subscribed_money >=", value, "subscribedMoney");
            return (Criteria) this;
        }

        public Criteria andSubscribedMoneyLessThan(String value) {
            addCriterion("subscribed_money <", value, "subscribedMoney");
            return (Criteria) this;
        }

        public Criteria andSubscribedMoneyLessThanOrEqualTo(String value) {
            addCriterion("subscribed_money <=", value, "subscribedMoney");
            return (Criteria) this;
        }

        public Criteria andSubscribedMoneyLike(String value) {
            addCriterion("subscribed_money like", value, "subscribedMoney");
            return (Criteria) this;
        }

        public Criteria andSubscribedMoneyNotLike(String value) {
            addCriterion("subscribed_money not like", value, "subscribedMoney");
            return (Criteria) this;
        }

        public Criteria andSubscribedMoneyIn(List<String> values) {
            addCriterion("subscribed_money in", values, "subscribedMoney");
            return (Criteria) this;
        }

        public Criteria andSubscribedMoneyNotIn(List<String> values) {
            addCriterion("subscribed_money not in", values, "subscribedMoney");
            return (Criteria) this;
        }

        public Criteria andSubscribedMoneyBetween(String value1, String value2) {
            addCriterion("subscribed_money between", value1, value2, "subscribedMoney");
            return (Criteria) this;
        }

        public Criteria andSubscribedMoneyNotBetween(String value1, String value2) {
            addCriterion("subscribed_money not between", value1, value2, "subscribedMoney");
            return (Criteria) this;
        }

        public Criteria andPaidMoneyIsNull() {
            addCriterion("paid_money is null");
            return (Criteria) this;
        }

        public Criteria andPaidMoneyIsNotNull() {
            addCriterion("paid_money is not null");
            return (Criteria) this;
        }

        public Criteria andPaidMoneyEqualTo(String value) {
            addCriterion("paid_money =", value, "paidMoney");
            return (Criteria) this;
        }

        public Criteria andPaidMoneyNotEqualTo(String value) {
            addCriterion("paid_money <>", value, "paidMoney");
            return (Criteria) this;
        }

        public Criteria andPaidMoneyGreaterThan(String value) {
            addCriterion("paid_money >", value, "paidMoney");
            return (Criteria) this;
        }

        public Criteria andPaidMoneyGreaterThanOrEqualTo(String value) {
            addCriterion("paid_money >=", value, "paidMoney");
            return (Criteria) this;
        }

        public Criteria andPaidMoneyLessThan(String value) {
            addCriterion("paid_money <", value, "paidMoney");
            return (Criteria) this;
        }

        public Criteria andPaidMoneyLessThanOrEqualTo(String value) {
            addCriterion("paid_money <=", value, "paidMoney");
            return (Criteria) this;
        }

        public Criteria andPaidMoneyLike(String value) {
            addCriterion("paid_money like", value, "paidMoney");
            return (Criteria) this;
        }

        public Criteria andPaidMoneyNotLike(String value) {
            addCriterion("paid_money not like", value, "paidMoney");
            return (Criteria) this;
        }

        public Criteria andPaidMoneyIn(List<String> values) {
            addCriterion("paid_money in", values, "paidMoney");
            return (Criteria) this;
        }

        public Criteria andPaidMoneyNotIn(List<String> values) {
            addCriterion("paid_money not in", values, "paidMoney");
            return (Criteria) this;
        }

        public Criteria andPaidMoneyBetween(String value1, String value2) {
            addCriterion("paid_money between", value1, value2, "paidMoney");
            return (Criteria) this;
        }

        public Criteria andPaidMoneyNotBetween(String value1, String value2) {
            addCriterion("paid_money not between", value1, value2, "paidMoney");
            return (Criteria) this;
        }

        public Criteria andPeriodizationIsNull() {
            addCriterion("periodization is null");
            return (Criteria) this;
        }

        public Criteria andPeriodizationIsNotNull() {
            addCriterion("periodization is not null");
            return (Criteria) this;
        }

        public Criteria andPeriodizationEqualTo(String value) {
            addCriterion("periodization =", value, "periodization");
            return (Criteria) this;
        }

        public Criteria andPeriodizationNotEqualTo(String value) {
            addCriterion("periodization <>", value, "periodization");
            return (Criteria) this;
        }

        public Criteria andPeriodizationGreaterThan(String value) {
            addCriterion("periodization >", value, "periodization");
            return (Criteria) this;
        }

        public Criteria andPeriodizationGreaterThanOrEqualTo(String value) {
            addCriterion("periodization >=", value, "periodization");
            return (Criteria) this;
        }

        public Criteria andPeriodizationLessThan(String value) {
            addCriterion("periodization <", value, "periodization");
            return (Criteria) this;
        }

        public Criteria andPeriodizationLessThanOrEqualTo(String value) {
            addCriterion("periodization <=", value, "periodization");
            return (Criteria) this;
        }

        public Criteria andPeriodizationLike(String value) {
            addCriterion("periodization like", value, "periodization");
            return (Criteria) this;
        }

        public Criteria andPeriodizationNotLike(String value) {
            addCriterion("periodization not like", value, "periodization");
            return (Criteria) this;
        }

        public Criteria andPeriodizationIn(List<String> values) {
            addCriterion("periodization in", values, "periodization");
            return (Criteria) this;
        }

        public Criteria andPeriodizationNotIn(List<String> values) {
            addCriterion("periodization not in", values, "periodization");
            return (Criteria) this;
        }

        public Criteria andPeriodizationBetween(String value1, String value2) {
            addCriterion("periodization between", value1, value2, "periodization");
            return (Criteria) this;
        }

        public Criteria andPeriodizationNotBetween(String value1, String value2) {
            addCriterion("periodization not between", value1, value2, "periodization");
            return (Criteria) this;
        }

        public Criteria andPaymenttermIsNull() {
            addCriterion("Paymentterm is null");
            return (Criteria) this;
        }

        public Criteria andPaymenttermIsNotNull() {
            addCriterion("Paymentterm is not null");
            return (Criteria) this;
        }

        public Criteria andPaymenttermEqualTo(String value) {
            addCriterion("Paymentterm =", value, "paymentterm");
            return (Criteria) this;
        }

        public Criteria andPaymenttermNotEqualTo(String value) {
            addCriterion("Paymentterm <>", value, "paymentterm");
            return (Criteria) this;
        }

        public Criteria andPaymenttermGreaterThan(String value) {
            addCriterion("Paymentterm >", value, "paymentterm");
            return (Criteria) this;
        }

        public Criteria andPaymenttermGreaterThanOrEqualTo(String value) {
            addCriterion("Paymentterm >=", value, "paymentterm");
            return (Criteria) this;
        }

        public Criteria andPaymenttermLessThan(String value) {
            addCriterion("Paymentterm <", value, "paymentterm");
            return (Criteria) this;
        }

        public Criteria andPaymenttermLessThanOrEqualTo(String value) {
            addCriterion("Paymentterm <=", value, "paymentterm");
            return (Criteria) this;
        }

        public Criteria andPaymenttermLike(String value) {
            addCriterion("Paymentterm like", value, "paymentterm");
            return (Criteria) this;
        }

        public Criteria andPaymenttermNotLike(String value) {
            addCriterion("Paymentterm not like", value, "paymentterm");
            return (Criteria) this;
        }

        public Criteria andPaymenttermIn(List<String> values) {
            addCriterion("Paymentterm in", values, "paymentterm");
            return (Criteria) this;
        }

        public Criteria andPaymenttermNotIn(List<String> values) {
            addCriterion("Paymentterm not in", values, "paymentterm");
            return (Criteria) this;
        }

        public Criteria andPaymenttermBetween(String value1, String value2) {
            addCriterion("Paymentterm between", value1, value2, "paymentterm");
            return (Criteria) this;
        }

        public Criteria andPaymenttermNotBetween(String value1, String value2) {
            addCriterion("Paymentterm not between", value1, value2, "paymentterm");
            return (Criteria) this;
        }

        public Criteria andHoldStateIsNull() {
            addCriterion("hold_state is null");
            return (Criteria) this;
        }

        public Criteria andHoldStateIsNotNull() {
            addCriterion("hold_state is not null");
            return (Criteria) this;
        }

        public Criteria andHoldStateEqualTo(String value) {
            addCriterion("hold_state =", value, "holdState");
            return (Criteria) this;
        }

        public Criteria andHoldStateNotEqualTo(String value) {
            addCriterion("hold_state <>", value, "holdState");
            return (Criteria) this;
        }

        public Criteria andHoldStateGreaterThan(String value) {
            addCriterion("hold_state >", value, "holdState");
            return (Criteria) this;
        }

        public Criteria andHoldStateGreaterThanOrEqualTo(String value) {
            addCriterion("hold_state >=", value, "holdState");
            return (Criteria) this;
        }

        public Criteria andHoldStateLessThan(String value) {
            addCriterion("hold_state <", value, "holdState");
            return (Criteria) this;
        }

        public Criteria andHoldStateLessThanOrEqualTo(String value) {
            addCriterion("hold_state <=", value, "holdState");
            return (Criteria) this;
        }

        public Criteria andHoldStateLike(String value) {
            addCriterion("hold_state like", value, "holdState");
            return (Criteria) this;
        }

        public Criteria andHoldStateNotLike(String value) {
            addCriterion("hold_state not like", value, "holdState");
            return (Criteria) this;
        }

        public Criteria andHoldStateIn(List<String> values) {
            addCriterion("hold_state in", values, "holdState");
            return (Criteria) this;
        }

        public Criteria andHoldStateNotIn(List<String> values) {
            addCriterion("hold_state not in", values, "holdState");
            return (Criteria) this;
        }

        public Criteria andHoldStateBetween(String value1, String value2) {
            addCriterion("hold_state between", value1, value2, "holdState");
            return (Criteria) this;
        }

        public Criteria andHoldStateNotBetween(String value1, String value2) {
            addCriterion("hold_state not between", value1, value2, "holdState");
            return (Criteria) this;
        }

        public Criteria andHoldNowIsNull() {
            addCriterion("hold_now is null");
            return (Criteria) this;
        }

        public Criteria andHoldNowIsNotNull() {
            addCriterion("hold_now is not null");
            return (Criteria) this;
        }

        public Criteria andHoldNowEqualTo(String value) {
            addCriterion("hold_now =", value, "holdNow");
            return (Criteria) this;
        }

        public Criteria andHoldNowNotEqualTo(String value) {
            addCriterion("hold_now <>", value, "holdNow");
            return (Criteria) this;
        }

        public Criteria andHoldNowGreaterThan(String value) {
            addCriterion("hold_now >", value, "holdNow");
            return (Criteria) this;
        }

        public Criteria andHoldNowGreaterThanOrEqualTo(String value) {
            addCriterion("hold_now >=", value, "holdNow");
            return (Criteria) this;
        }

        public Criteria andHoldNowLessThan(String value) {
            addCriterion("hold_now <", value, "holdNow");
            return (Criteria) this;
        }

        public Criteria andHoldNowLessThanOrEqualTo(String value) {
            addCriterion("hold_now <=", value, "holdNow");
            return (Criteria) this;
        }

        public Criteria andHoldNowLike(String value) {
            addCriterion("hold_now like", value, "holdNow");
            return (Criteria) this;
        }

        public Criteria andHoldNowNotLike(String value) {
            addCriterion("hold_now not like", value, "holdNow");
            return (Criteria) this;
        }

        public Criteria andHoldNowIn(List<String> values) {
            addCriterion("hold_now in", values, "holdNow");
            return (Criteria) this;
        }

        public Criteria andHoldNowNotIn(List<String> values) {
            addCriterion("hold_now not in", values, "holdNow");
            return (Criteria) this;
        }

        public Criteria andHoldNowBetween(String value1, String value2) {
            addCriterion("hold_now between", value1, value2, "holdNow");
            return (Criteria) this;
        }

        public Criteria andHoldNowNotBetween(String value1, String value2) {
            addCriterion("hold_now not between", value1, value2, "holdNow");
            return (Criteria) this;
        }

        public Criteria andPersentNowIsNull() {
            addCriterion("persent_now is null");
            return (Criteria) this;
        }

        public Criteria andPersentNowIsNotNull() {
            addCriterion("persent_now is not null");
            return (Criteria) this;
        }

        public Criteria andPersentNowEqualTo(String value) {
            addCriterion("persent_now =", value, "persentNow");
            return (Criteria) this;
        }

        public Criteria andPersentNowNotEqualTo(String value) {
            addCriterion("persent_now <>", value, "persentNow");
            return (Criteria) this;
        }

        public Criteria andPersentNowGreaterThan(String value) {
            addCriterion("persent_now >", value, "persentNow");
            return (Criteria) this;
        }

        public Criteria andPersentNowGreaterThanOrEqualTo(String value) {
            addCriterion("persent_now >=", value, "persentNow");
            return (Criteria) this;
        }

        public Criteria andPersentNowLessThan(String value) {
            addCriterion("persent_now <", value, "persentNow");
            return (Criteria) this;
        }

        public Criteria andPersentNowLessThanOrEqualTo(String value) {
            addCriterion("persent_now <=", value, "persentNow");
            return (Criteria) this;
        }

        public Criteria andPersentNowLike(String value) {
            addCriterion("persent_now like", value, "persentNow");
            return (Criteria) this;
        }

        public Criteria andPersentNowNotLike(String value) {
            addCriterion("persent_now not like", value, "persentNow");
            return (Criteria) this;
        }

        public Criteria andPersentNowIn(List<String> values) {
            addCriterion("persent_now in", values, "persentNow");
            return (Criteria) this;
        }

        public Criteria andPersentNowNotIn(List<String> values) {
            addCriterion("persent_now not in", values, "persentNow");
            return (Criteria) this;
        }

        public Criteria andPersentNowBetween(String value1, String value2) {
            addCriterion("persent_now between", value1, value2, "persentNow");
            return (Criteria) this;
        }

        public Criteria andPersentNowNotBetween(String value1, String value2) {
            addCriterion("persent_now not between", value1, value2, "persentNow");
            return (Criteria) this;
        }

        public Criteria andReasonIdIsNull() {
            addCriterion("reason_id is null");
            return (Criteria) this;
        }

        public Criteria andReasonIdIsNotNull() {
            addCriterion("reason_id is not null");
            return (Criteria) this;
        }

        public Criteria andReasonIdEqualTo(String value) {
            addCriterion("reason_id =", value, "reasonId");
            return (Criteria) this;
        }

        public Criteria andReasonIdNotEqualTo(String value) {
            addCriterion("reason_id <>", value, "reasonId");
            return (Criteria) this;
        }

        public Criteria andReasonIdGreaterThan(String value) {
            addCriterion("reason_id >", value, "reasonId");
            return (Criteria) this;
        }

        public Criteria andReasonIdGreaterThanOrEqualTo(String value) {
            addCriterion("reason_id >=", value, "reasonId");
            return (Criteria) this;
        }

        public Criteria andReasonIdLessThan(String value) {
            addCriterion("reason_id <", value, "reasonId");
            return (Criteria) this;
        }

        public Criteria andReasonIdLessThanOrEqualTo(String value) {
            addCriterion("reason_id <=", value, "reasonId");
            return (Criteria) this;
        }

        public Criteria andReasonIdLike(String value) {
            addCriterion("reason_id like", value, "reasonId");
            return (Criteria) this;
        }

        public Criteria andReasonIdNotLike(String value) {
            addCriterion("reason_id not like", value, "reasonId");
            return (Criteria) this;
        }

        public Criteria andReasonIdIn(List<String> values) {
            addCriterion("reason_id in", values, "reasonId");
            return (Criteria) this;
        }

        public Criteria andReasonIdNotIn(List<String> values) {
            addCriterion("reason_id not in", values, "reasonId");
            return (Criteria) this;
        }

        public Criteria andReasonIdBetween(String value1, String value2) {
            addCriterion("reason_id between", value1, value2, "reasonId");
            return (Criteria) this;
        }

        public Criteria andReasonIdNotBetween(String value1, String value2) {
            addCriterion("reason_id not between", value1, value2, "reasonId");
            return (Criteria) this;
        }

        public Criteria andPartnerNameIsNull() {
            addCriterion("partner_name is null");
            return (Criteria) this;
        }

        public Criteria andPartnerNameIsNotNull() {
            addCriterion("partner_name is not null");
            return (Criteria) this;
        }

        public Criteria andPartnerNameEqualTo(String value) {
            addCriterion("partner_name =", value, "partnerName");
            return (Criteria) this;
        }

        public Criteria andPartnerNameNotEqualTo(String value) {
            addCriterion("partner_name <>", value, "partnerName");
            return (Criteria) this;
        }

        public Criteria andPartnerNameGreaterThan(String value) {
            addCriterion("partner_name >", value, "partnerName");
            return (Criteria) this;
        }

        public Criteria andPartnerNameGreaterThanOrEqualTo(String value) {
            addCriterion("partner_name >=", value, "partnerName");
            return (Criteria) this;
        }

        public Criteria andPartnerNameLessThan(String value) {
            addCriterion("partner_name <", value, "partnerName");
            return (Criteria) this;
        }

        public Criteria andPartnerNameLessThanOrEqualTo(String value) {
            addCriterion("partner_name <=", value, "partnerName");
            return (Criteria) this;
        }

        public Criteria andPartnerNameLike(String value) {
            addCriterion("partner_name like", value, "partnerName");
            return (Criteria) this;
        }

        public Criteria andPartnerNameNotLike(String value) {
            addCriterion("partner_name not like", value, "partnerName");
            return (Criteria) this;
        }

        public Criteria andPartnerNameIn(List<String> values) {
            addCriterion("partner_name in", values, "partnerName");
            return (Criteria) this;
        }

        public Criteria andPartnerNameNotIn(List<String> values) {
            addCriterion("partner_name not in", values, "partnerName");
            return (Criteria) this;
        }

        public Criteria andPartnerNameBetween(String value1, String value2) {
            addCriterion("partner_name between", value1, value2, "partnerName");
            return (Criteria) this;
        }

        public Criteria andPartnerNameNotBetween(String value1, String value2) {
            addCriterion("partner_name not between", value1, value2, "partnerName");
            return (Criteria) this;
        }

        public Criteria andPartnerTypeIsNull() {
            addCriterion("partner_type is null");
            return (Criteria) this;
        }

        public Criteria andPartnerTypeIsNotNull() {
            addCriterion("partner_type is not null");
            return (Criteria) this;
        }

        public Criteria andPartnerTypeEqualTo(String value) {
            addCriterion("partner_type =", value, "partnerType");
            return (Criteria) this;
        }

        public Criteria andPartnerTypeNotEqualTo(String value) {
            addCriterion("partner_type <>", value, "partnerType");
            return (Criteria) this;
        }

        public Criteria andPartnerTypeGreaterThan(String value) {
            addCriterion("partner_type >", value, "partnerType");
            return (Criteria) this;
        }

        public Criteria andPartnerTypeGreaterThanOrEqualTo(String value) {
            addCriterion("partner_type >=", value, "partnerType");
            return (Criteria) this;
        }

        public Criteria andPartnerTypeLessThan(String value) {
            addCriterion("partner_type <", value, "partnerType");
            return (Criteria) this;
        }

        public Criteria andPartnerTypeLessThanOrEqualTo(String value) {
            addCriterion("partner_type <=", value, "partnerType");
            return (Criteria) this;
        }

        public Criteria andPartnerTypeLike(String value) {
            addCriterion("partner_type like", value, "partnerType");
            return (Criteria) this;
        }

        public Criteria andPartnerTypeNotLike(String value) {
            addCriterion("partner_type not like", value, "partnerType");
            return (Criteria) this;
        }

        public Criteria andPartnerTypeIn(List<String> values) {
            addCriterion("partner_type in", values, "partnerType");
            return (Criteria) this;
        }

        public Criteria andPartnerTypeNotIn(List<String> values) {
            addCriterion("partner_type not in", values, "partnerType");
            return (Criteria) this;
        }

        public Criteria andPartnerTypeBetween(String value1, String value2) {
            addCriterion("partner_type between", value1, value2, "partnerType");
            return (Criteria) this;
        }

        public Criteria andPartnerTypeNotBetween(String value1, String value2) {
            addCriterion("partner_type not between", value1, value2, "partnerType");
            return (Criteria) this;
        }

        public Criteria andCapitalPropertyIsNull() {
            addCriterion("capital_property is null");
            return (Criteria) this;
        }

        public Criteria andCapitalPropertyIsNotNull() {
            addCriterion("capital_property is not null");
            return (Criteria) this;
        }

        public Criteria andCapitalPropertyEqualTo(String value) {
            addCriterion("capital_property =", value, "capitalProperty");
            return (Criteria) this;
        }

        public Criteria andCapitalPropertyNotEqualTo(String value) {
            addCriterion("capital_property <>", value, "capitalProperty");
            return (Criteria) this;
        }

        public Criteria andCapitalPropertyGreaterThan(String value) {
            addCriterion("capital_property >", value, "capitalProperty");
            return (Criteria) this;
        }

        public Criteria andCapitalPropertyGreaterThanOrEqualTo(String value) {
            addCriterion("capital_property >=", value, "capitalProperty");
            return (Criteria) this;
        }

        public Criteria andCapitalPropertyLessThan(String value) {
            addCriterion("capital_property <", value, "capitalProperty");
            return (Criteria) this;
        }

        public Criteria andCapitalPropertyLessThanOrEqualTo(String value) {
            addCriterion("capital_property <=", value, "capitalProperty");
            return (Criteria) this;
        }

        public Criteria andCapitalPropertyLike(String value) {
            addCriterion("capital_property like", value, "capitalProperty");
            return (Criteria) this;
        }

        public Criteria andCapitalPropertyNotLike(String value) {
            addCriterion("capital_property not like", value, "capitalProperty");
            return (Criteria) this;
        }

        public Criteria andCapitalPropertyIn(List<String> values) {
            addCriterion("capital_property in", values, "capitalProperty");
            return (Criteria) this;
        }

        public Criteria andCapitalPropertyNotIn(List<String> values) {
            addCriterion("capital_property not in", values, "capitalProperty");
            return (Criteria) this;
        }

        public Criteria andCapitalPropertyBetween(String value1, String value2) {
            addCriterion("capital_property between", value1, value2, "capitalProperty");
            return (Criteria) this;
        }

        public Criteria andCapitalPropertyNotBetween(String value1, String value2) {
            addCriterion("capital_property not between", value1, value2, "capitalProperty");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fund_partner_rel
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fund_partner_rel
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}