package com.example.demo.bean;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table fund_money
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class FundMoney {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_money.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * Database Column Remarks:
     *   关联基金id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_money.fund_id
     *
     * @mbg.generated
     */
    private String fundId;

    /**
     * Database Column Remarks:
     *   打款人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_money.remit_name
     *
     * @mbg.generated
     */
    private String remitName;

    /**
     * Database Column Remarks:
     *   收款人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_money.collection_name
     *
     * @mbg.generated
     */
    private String collectionName;

    /**
     * Database Column Remarks:
     *   打款金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_money.money
     *
     * @mbg.generated
     */
    private String money;

    /**
     * Database Column Remarks:
     *   收款账号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_money.account
     *
     * @mbg.generated
     */
    private String account;

    /**
     * Database Column Remarks:
     *   删除状态（0：删除；1：未删除）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_money.deletestatus
     *
     * @mbg.generated
     */
    private Integer deletestatus;

    /**
     * Database Column Remarks:
     *   打款时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_money.pay_time
     *
     * @mbg.generated
     */
    private String payTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_money.id
     *
     * @return the value of fund_money.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_money.id
     *
     * @param id the value for fund_money.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_money.fund_id
     *
     * @return the value of fund_money.fund_id
     *
     * @mbg.generated
     */
    public String getFundId() {
        return fundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_money.fund_id
     *
     * @param fundId the value for fund_money.fund_id
     *
     * @mbg.generated
     */
    public void setFundId(String fundId) {
        this.fundId = fundId == null ? null : fundId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_money.remit_name
     *
     * @return the value of fund_money.remit_name
     *
     * @mbg.generated
     */
    public String getRemitName() {
        return remitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_money.remit_name
     *
     * @param remitName the value for fund_money.remit_name
     *
     * @mbg.generated
     */
    public void setRemitName(String remitName) {
        this.remitName = remitName == null ? null : remitName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_money.collection_name
     *
     * @return the value of fund_money.collection_name
     *
     * @mbg.generated
     */
    public String getCollectionName() {
        return collectionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_money.collection_name
     *
     * @param collectionName the value for fund_money.collection_name
     *
     * @mbg.generated
     */
    public void setCollectionName(String collectionName) {
        this.collectionName = collectionName == null ? null : collectionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_money.money
     *
     * @return the value of fund_money.money
     *
     * @mbg.generated
     */
    public String getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_money.money
     *
     * @param money the value for fund_money.money
     *
     * @mbg.generated
     */
    public void setMoney(String money) {
        this.money = money == null ? null : money.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_money.account
     *
     * @return the value of fund_money.account
     *
     * @mbg.generated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_money.account
     *
     * @param account the value for fund_money.account
     *
     * @mbg.generated
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_money.deletestatus
     *
     * @return the value of fund_money.deletestatus
     *
     * @mbg.generated
     */
    public Integer getDeletestatus() {
        return deletestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_money.deletestatus
     *
     * @param deletestatus the value for fund_money.deletestatus
     *
     * @mbg.generated
     */
    public void setDeletestatus(Integer deletestatus) {
        this.deletestatus = deletestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_money.pay_time
     *
     * @return the value of fund_money.pay_time
     *
     * @mbg.generated
     */
    public String getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_money.pay_time
     *
     * @param payTime the value for fund_money.pay_time
     *
     * @mbg.generated
     */
    public void setPayTime(String payTime) {
        this.payTime = payTime == null ? null : payTime.trim();
    }
}