package com.example.demo.bean;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table guest_user_rel
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class GuestUserRel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guest_user_rel.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guest_user_rel.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guest_user_rel.guest_id
     *
     * @mbg.generated
     */
    private String guestId;

    /**
     * Database Column Remarks:
     *   删除标记 1有效
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guest_user_rel.deleted_status
     *
     * @mbg.generated
     */
    private Integer deletedStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guest_user_rel.id
     *
     * @return the value of guest_user_rel.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guest_user_rel.id
     *
     * @param id the value for guest_user_rel.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guest_user_rel.user_id
     *
     * @return the value of guest_user_rel.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guest_user_rel.user_id
     *
     * @param userId the value for guest_user_rel.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guest_user_rel.guest_id
     *
     * @return the value of guest_user_rel.guest_id
     *
     * @mbg.generated
     */
    public String getGuestId() {
        return guestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guest_user_rel.guest_id
     *
     * @param guestId the value for guest_user_rel.guest_id
     *
     * @mbg.generated
     */
    public void setGuestId(String guestId) {
        this.guestId = guestId == null ? null : guestId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guest_user_rel.deleted_status
     *
     * @return the value of guest_user_rel.deleted_status
     *
     * @mbg.generated
     */
    public Integer getDeletedStatus() {
        return deletedStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guest_user_rel.deleted_status
     *
     * @param deletedStatus the value for guest_user_rel.deleted_status
     *
     * @mbg.generated
     */
    public void setDeletedStatus(Integer deletedStatus) {
        this.deletedStatus = deletedStatus;
    }
}