package com.example.demo.bean;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table image_file
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class ImageFile {
    /**
     * Database Column Remarks:
     *   主键 UUID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_file.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * Database Column Remarks:
     *   图片种类（项目、用户）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_file.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     * Database Column Remarks:
     *   是否删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_file.is_del
     *
     * @mbg.generated
     */
    private Integer isDel;

    /**
     * Database Column Remarks:
     *   上传时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_file.add_time
     *
     * @mbg.generated
     */
    private Date addTime;

    /**
     * Database Column Remarks:
     *   排序（保留字段）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_file.sort
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     * Database Column Remarks:
     *   图片名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_file.file_name
     *
     * @mbg.generated
     */
    private String fileName;

    /**
     * Database Column Remarks:
     *   外键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_file.foreign_id
     *
     * @mbg.generated
     */
    private String foreignId;

    /**
     * Database Column Remarks:
     *   文件后缀名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_file.file_type
     *
     * @mbg.generated
     */
    private String fileType;

    /**
     * Database Column Remarks:
     *   文件内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_file.file_content
     *
     * @mbg.generated
     */
    private byte[] fileContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_file.id
     *
     * @return the value of image_file.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_file.id
     *
     * @param id the value for image_file.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_file.type
     *
     * @return the value of image_file.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_file.type
     *
     * @param type the value for image_file.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_file.is_del
     *
     * @return the value of image_file.is_del
     *
     * @mbg.generated
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_file.is_del
     *
     * @param isDel the value for image_file.is_del
     *
     * @mbg.generated
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_file.add_time
     *
     * @return the value of image_file.add_time
     *
     * @mbg.generated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_file.add_time
     *
     * @param addTime the value for image_file.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_file.sort
     *
     * @return the value of image_file.sort
     *
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_file.sort
     *
     * @param sort the value for image_file.sort
     *
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_file.file_name
     *
     * @return the value of image_file.file_name
     *
     * @mbg.generated
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_file.file_name
     *
     * @param fileName the value for image_file.file_name
     *
     * @mbg.generated
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_file.foreign_id
     *
     * @return the value of image_file.foreign_id
     *
     * @mbg.generated
     */
    public String getForeignId() {
        return foreignId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_file.foreign_id
     *
     * @param foreignId the value for image_file.foreign_id
     *
     * @mbg.generated
     */
    public void setForeignId(String foreignId) {
        this.foreignId = foreignId == null ? null : foreignId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_file.file_type
     *
     * @return the value of image_file.file_type
     *
     * @mbg.generated
     */
    public String getFileType() {
        return fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_file.file_type
     *
     * @param fileType the value for image_file.file_type
     *
     * @mbg.generated
     */
    public void setFileType(String fileType) {
        this.fileType = fileType == null ? null : fileType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_file.file_content
     *
     * @return the value of image_file.file_content
     *
     * @mbg.generated
     */
    public byte[] getFileContent() {
        return fileContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_file.file_content
     *
     * @param fileContent the value for image_file.file_content
     *
     * @mbg.generated
     */
    public void setFileContent(byte[] fileContent) {
        this.fileContent = fileContent;
    }
}