package com.example.demo.bean;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table item_invest
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class ItemInvest {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_invest.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * Database Column Remarks:
     *   股权项目id  item表的主键ID 并非stock_item
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_invest.stockitemid
     *
     * @mbg.generated
     */
    private String stockitemid;

    /**
     * Database Column Remarks:
     *   关联基金  -1代表 未投资
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_invest.fund_id
     *
     * @mbg.generated
     */
    private String fundId;

    /**
     * Database Column Remarks:
     *   投资时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_invest.invest_date
     *
     * @mbg.generated
     */
    private Date investDate;

    /**
     * Database Column Remarks:
     *   变动类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_invest.changed_type
     *
     * @mbg.generated
     */
    private String changedType;

    /**
     * Database Column Remarks:
     *   投资类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_invest.invest_type
     *
     * @mbg.generated
     */
    private String investType;

    /**
     * Database Column Remarks:
     *   投资金额（万元）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_invest.invest_loan
     *
     * @mbg.generated
     */
    private BigDecimal investLoan;

    /**
     * Database Column Remarks:
     *   项目估值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_invest.Project_valuation
     *
     * @mbg.generated
     */
    private BigDecimal projectValuation;

    /**
     * Database Column Remarks:
     *   项目总股本
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_invest.Total
     *
     * @mbg.generated
     */
    private BigDecimal total;

    /**
     * Database Column Remarks:
     *   资金总额（本次投资金额）  --  目前含义:变动金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_invest.Total_capital
     *
     * @mbg.generated
     */
    private BigDecimal totalCapital;

    /**
     * Database Column Remarks:
     *   期初持股
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_invest.Begin_holding
     *
     * @mbg.generated
     */
    private BigDecimal beginHolding;

    /**
     * Database Column Remarks:
     *   期末持股
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_invest.Final_holding
     *
     * @mbg.generated
     */
    private BigDecimal finalHolding;

    /**
     * Database Column Remarks:
     *   变化数量（万股）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_invest.invest_number
     *
     * @mbg.generated
     */
    private BigDecimal investNumber;

    /**
     * Database Column Remarks:
     *   投资收益
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_invest.equity_earnings
     *
     * @mbg.generated
     */
    private Double equityEarnings;

    /**
     * Database Column Remarks:
     *   变化均价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_invest.Change_fold
     *
     * @mbg.generated
     */
    private BigDecimal changeFold;

    /**
     * Database Column Remarks:
     *   退出倍数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_invest.Exit_multiple
     *
     * @mbg.generated
     */
    private String exitMultiple;

    /**
     * Database Column Remarks:
     *   IRR
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_invest.IRR
     *
     * @mbg.generated
     */
    private String irr;

    /**
     * Database Column Remarks:
     *   投资成本
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_invest.invest_cost
     *
     * @mbg.generated
     */
    private Double investCost;

    /**
     * Database Column Remarks:
     *   股本
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_invest.equity
     *
     * @mbg.generated
     */
    private BigDecimal equity;

    /**
     * Database Column Remarks:
     *   是否是初始投资  1:是  0：否
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_invest.isinit
     *
     * @mbg.generated
     */
    private Integer isinit;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_invest.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_invest.update_date
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     * Database Column Remarks:
     *   删除标志
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_invest.isdeteled
     *
     * @mbg.generated
     */
    private Integer isdeteled;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_invest.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     * Database Column Remarks:
     *   当前成本（元/股）   新增字段
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_invest.currentCost
     *
     * @mbg.generated
     */
    private String currentcost;

    /**
     * Database Column Remarks:
     *   上一条的成本
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_invest.lastCost
     *
     * @mbg.generated
     */
    private String lastcost;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_invest.id
     *
     * @return the value of item_invest.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_invest.id
     *
     * @param id the value for item_invest.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_invest.stockitemid
     *
     * @return the value of item_invest.stockitemid
     *
     * @mbg.generated
     */
    public String getStockitemid() {
        return stockitemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_invest.stockitemid
     *
     * @param stockitemid the value for item_invest.stockitemid
     *
     * @mbg.generated
     */
    public void setStockitemid(String stockitemid) {
        this.stockitemid = stockitemid == null ? null : stockitemid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_invest.fund_id
     *
     * @return the value of item_invest.fund_id
     *
     * @mbg.generated
     */
    public String getFundId() {
        return fundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_invest.fund_id
     *
     * @param fundId the value for item_invest.fund_id
     *
     * @mbg.generated
     */
    public void setFundId(String fundId) {
        this.fundId = fundId == null ? null : fundId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_invest.invest_date
     *
     * @return the value of item_invest.invest_date
     *
     * @mbg.generated
     */
    public Date getInvestDate() {
        return investDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_invest.invest_date
     *
     * @param investDate the value for item_invest.invest_date
     *
     * @mbg.generated
     */
    public void setInvestDate(Date investDate) {
        this.investDate = investDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_invest.changed_type
     *
     * @return the value of item_invest.changed_type
     *
     * @mbg.generated
     */
    public String getChangedType() {
        return changedType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_invest.changed_type
     *
     * @param changedType the value for item_invest.changed_type
     *
     * @mbg.generated
     */
    public void setChangedType(String changedType) {
        this.changedType = changedType == null ? null : changedType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_invest.invest_type
     *
     * @return the value of item_invest.invest_type
     *
     * @mbg.generated
     */
    public String getInvestType() {
        return investType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_invest.invest_type
     *
     * @param investType the value for item_invest.invest_type
     *
     * @mbg.generated
     */
    public void setInvestType(String investType) {
        this.investType = investType == null ? null : investType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_invest.invest_loan
     *
     * @return the value of item_invest.invest_loan
     *
     * @mbg.generated
     */
    public BigDecimal getInvestLoan() {
        return investLoan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_invest.invest_loan
     *
     * @param investLoan the value for item_invest.invest_loan
     *
     * @mbg.generated
     */
    public void setInvestLoan(BigDecimal investLoan) {
        this.investLoan = investLoan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_invest.Project_valuation
     *
     * @return the value of item_invest.Project_valuation
     *
     * @mbg.generated
     */
    public BigDecimal getProjectValuation() {
        return projectValuation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_invest.Project_valuation
     *
     * @param projectValuation the value for item_invest.Project_valuation
     *
     * @mbg.generated
     */
    public void setProjectValuation(BigDecimal projectValuation) {
        this.projectValuation = projectValuation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_invest.Total
     *
     * @return the value of item_invest.Total
     *
     * @mbg.generated
     */
    public BigDecimal getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_invest.Total
     *
     * @param total the value for item_invest.Total
     *
     * @mbg.generated
     */
    public void setTotal(BigDecimal total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_invest.Total_capital
     *
     * @return the value of item_invest.Total_capital
     *
     * @mbg.generated
     */
    public BigDecimal getTotalCapital() {
        return totalCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_invest.Total_capital
     *
     * @param totalCapital the value for item_invest.Total_capital
     *
     * @mbg.generated
     */
    public void setTotalCapital(BigDecimal totalCapital) {
        this.totalCapital = totalCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_invest.Begin_holding
     *
     * @return the value of item_invest.Begin_holding
     *
     * @mbg.generated
     */
    public BigDecimal getBeginHolding() {
        return beginHolding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_invest.Begin_holding
     *
     * @param beginHolding the value for item_invest.Begin_holding
     *
     * @mbg.generated
     */
    public void setBeginHolding(BigDecimal beginHolding) {
        this.beginHolding = beginHolding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_invest.Final_holding
     *
     * @return the value of item_invest.Final_holding
     *
     * @mbg.generated
     */
    public BigDecimal getFinalHolding() {
        return finalHolding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_invest.Final_holding
     *
     * @param finalHolding the value for item_invest.Final_holding
     *
     * @mbg.generated
     */
    public void setFinalHolding(BigDecimal finalHolding) {
        this.finalHolding = finalHolding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_invest.invest_number
     *
     * @return the value of item_invest.invest_number
     *
     * @mbg.generated
     */
    public BigDecimal getInvestNumber() {
        return investNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_invest.invest_number
     *
     * @param investNumber the value for item_invest.invest_number
     *
     * @mbg.generated
     */
    public void setInvestNumber(BigDecimal investNumber) {
        this.investNumber = investNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_invest.equity_earnings
     *
     * @return the value of item_invest.equity_earnings
     *
     * @mbg.generated
     */
    public Double getEquityEarnings() {
        return equityEarnings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_invest.equity_earnings
     *
     * @param equityEarnings the value for item_invest.equity_earnings
     *
     * @mbg.generated
     */
    public void setEquityEarnings(Double equityEarnings) {
        this.equityEarnings = equityEarnings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_invest.Change_fold
     *
     * @return the value of item_invest.Change_fold
     *
     * @mbg.generated
     */
    public BigDecimal getChangeFold() {
        return changeFold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_invest.Change_fold
     *
     * @param changeFold the value for item_invest.Change_fold
     *
     * @mbg.generated
     */
    public void setChangeFold(BigDecimal changeFold) {
        this.changeFold = changeFold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_invest.Exit_multiple
     *
     * @return the value of item_invest.Exit_multiple
     *
     * @mbg.generated
     */
    public String getExitMultiple() {
        return exitMultiple;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_invest.Exit_multiple
     *
     * @param exitMultiple the value for item_invest.Exit_multiple
     *
     * @mbg.generated
     */
    public void setExitMultiple(String exitMultiple) {
        this.exitMultiple = exitMultiple == null ? null : exitMultiple.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_invest.IRR
     *
     * @return the value of item_invest.IRR
     *
     * @mbg.generated
     */
    public String getIrr() {
        return irr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_invest.IRR
     *
     * @param irr the value for item_invest.IRR
     *
     * @mbg.generated
     */
    public void setIrr(String irr) {
        this.irr = irr == null ? null : irr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_invest.invest_cost
     *
     * @return the value of item_invest.invest_cost
     *
     * @mbg.generated
     */
    public Double getInvestCost() {
        return investCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_invest.invest_cost
     *
     * @param investCost the value for item_invest.invest_cost
     *
     * @mbg.generated
     */
    public void setInvestCost(Double investCost) {
        this.investCost = investCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_invest.equity
     *
     * @return the value of item_invest.equity
     *
     * @mbg.generated
     */
    public BigDecimal getEquity() {
        return equity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_invest.equity
     *
     * @param equity the value for item_invest.equity
     *
     * @mbg.generated
     */
    public void setEquity(BigDecimal equity) {
        this.equity = equity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_invest.isinit
     *
     * @return the value of item_invest.isinit
     *
     * @mbg.generated
     */
    public Integer getIsinit() {
        return isinit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_invest.isinit
     *
     * @param isinit the value for item_invest.isinit
     *
     * @mbg.generated
     */
    public void setIsinit(Integer isinit) {
        this.isinit = isinit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_invest.create_date
     *
     * @return the value of item_invest.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_invest.create_date
     *
     * @param createDate the value for item_invest.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_invest.update_date
     *
     * @return the value of item_invest.update_date
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_invest.update_date
     *
     * @param updateDate the value for item_invest.update_date
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_invest.isdeteled
     *
     * @return the value of item_invest.isdeteled
     *
     * @mbg.generated
     */
    public Integer getIsdeteled() {
        return isdeteled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_invest.isdeteled
     *
     * @param isdeteled the value for item_invest.isdeteled
     *
     * @mbg.generated
     */
    public void setIsdeteled(Integer isdeteled) {
        this.isdeteled = isdeteled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_invest.remarks
     *
     * @return the value of item_invest.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_invest.remarks
     *
     * @param remarks the value for item_invest.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_invest.currentCost
     *
     * @return the value of item_invest.currentCost
     *
     * @mbg.generated
     */
    public String getCurrentcost() {
        return currentcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_invest.currentCost
     *
     * @param currentcost the value for item_invest.currentCost
     *
     * @mbg.generated
     */
    public void setCurrentcost(String currentcost) {
        this.currentcost = currentcost == null ? null : currentcost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_invest.lastCost
     *
     * @return the value of item_invest.lastCost
     *
     * @mbg.generated
     */
    public String getLastcost() {
        return lastcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_invest.lastCost
     *
     * @param lastcost the value for item_invest.lastCost
     *
     * @mbg.generated
     */
    public void setLastcost(String lastcost) {
        this.lastcost = lastcost == null ? null : lastcost.trim();
    }
}