package com.example.demo.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ItemRemittanceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table item_remittance
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table item_remittance
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table item_remittance
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_remittance
     *
     * @mbg.generated
     */
    public ItemRemittanceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_remittance
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_remittance
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_remittance
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_remittance
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_remittance
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_remittance
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_remittance
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_remittance
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_remittance
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_remittance
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table item_remittance
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andRemittanceDateIsNull() {
            addCriterion("remittance_date is null");
            return (Criteria) this;
        }

        public Criteria andRemittanceDateIsNotNull() {
            addCriterion("remittance_date is not null");
            return (Criteria) this;
        }

        public Criteria andRemittanceDateEqualTo(String value) {
            addCriterion("remittance_date =", value, "remittanceDate");
            return (Criteria) this;
        }

        public Criteria andRemittanceDateNotEqualTo(String value) {
            addCriterion("remittance_date <>", value, "remittanceDate");
            return (Criteria) this;
        }

        public Criteria andRemittanceDateGreaterThan(String value) {
            addCriterion("remittance_date >", value, "remittanceDate");
            return (Criteria) this;
        }

        public Criteria andRemittanceDateGreaterThanOrEqualTo(String value) {
            addCriterion("remittance_date >=", value, "remittanceDate");
            return (Criteria) this;
        }

        public Criteria andRemittanceDateLessThan(String value) {
            addCriterion("remittance_date <", value, "remittanceDate");
            return (Criteria) this;
        }

        public Criteria andRemittanceDateLessThanOrEqualTo(String value) {
            addCriterion("remittance_date <=", value, "remittanceDate");
            return (Criteria) this;
        }

        public Criteria andRemittanceDateLike(String value) {
            addCriterion("remittance_date like", value, "remittanceDate");
            return (Criteria) this;
        }

        public Criteria andRemittanceDateNotLike(String value) {
            addCriterion("remittance_date not like", value, "remittanceDate");
            return (Criteria) this;
        }

        public Criteria andRemittanceDateIn(List<String> values) {
            addCriterion("remittance_date in", values, "remittanceDate");
            return (Criteria) this;
        }

        public Criteria andRemittanceDateNotIn(List<String> values) {
            addCriterion("remittance_date not in", values, "remittanceDate");
            return (Criteria) this;
        }

        public Criteria andRemittanceDateBetween(String value1, String value2) {
            addCriterion("remittance_date between", value1, value2, "remittanceDate");
            return (Criteria) this;
        }

        public Criteria andRemittanceDateNotBetween(String value1, String value2) {
            addCriterion("remittance_date not between", value1, value2, "remittanceDate");
            return (Criteria) this;
        }

        public Criteria andRemittanceUserIsNull() {
            addCriterion("remittance_user is null");
            return (Criteria) this;
        }

        public Criteria andRemittanceUserIsNotNull() {
            addCriterion("remittance_user is not null");
            return (Criteria) this;
        }

        public Criteria andRemittanceUserEqualTo(String value) {
            addCriterion("remittance_user =", value, "remittanceUser");
            return (Criteria) this;
        }

        public Criteria andRemittanceUserNotEqualTo(String value) {
            addCriterion("remittance_user <>", value, "remittanceUser");
            return (Criteria) this;
        }

        public Criteria andRemittanceUserGreaterThan(String value) {
            addCriterion("remittance_user >", value, "remittanceUser");
            return (Criteria) this;
        }

        public Criteria andRemittanceUserGreaterThanOrEqualTo(String value) {
            addCriterion("remittance_user >=", value, "remittanceUser");
            return (Criteria) this;
        }

        public Criteria andRemittanceUserLessThan(String value) {
            addCriterion("remittance_user <", value, "remittanceUser");
            return (Criteria) this;
        }

        public Criteria andRemittanceUserLessThanOrEqualTo(String value) {
            addCriterion("remittance_user <=", value, "remittanceUser");
            return (Criteria) this;
        }

        public Criteria andRemittanceUserLike(String value) {
            addCriterion("remittance_user like", value, "remittanceUser");
            return (Criteria) this;
        }

        public Criteria andRemittanceUserNotLike(String value) {
            addCriterion("remittance_user not like", value, "remittanceUser");
            return (Criteria) this;
        }

        public Criteria andRemittanceUserIn(List<String> values) {
            addCriterion("remittance_user in", values, "remittanceUser");
            return (Criteria) this;
        }

        public Criteria andRemittanceUserNotIn(List<String> values) {
            addCriterion("remittance_user not in", values, "remittanceUser");
            return (Criteria) this;
        }

        public Criteria andRemittanceUserBetween(String value1, String value2) {
            addCriterion("remittance_user between", value1, value2, "remittanceUser");
            return (Criteria) this;
        }

        public Criteria andRemittanceUserNotBetween(String value1, String value2) {
            addCriterion("remittance_user not between", value1, value2, "remittanceUser");
            return (Criteria) this;
        }

        public Criteria andRemittanceAmountIsNull() {
            addCriterion("remittance_amount is null");
            return (Criteria) this;
        }

        public Criteria andRemittanceAmountIsNotNull() {
            addCriterion("remittance_amount is not null");
            return (Criteria) this;
        }

        public Criteria andRemittanceAmountEqualTo(String value) {
            addCriterion("remittance_amount =", value, "remittanceAmount");
            return (Criteria) this;
        }

        public Criteria andRemittanceAmountNotEqualTo(String value) {
            addCriterion("remittance_amount <>", value, "remittanceAmount");
            return (Criteria) this;
        }

        public Criteria andRemittanceAmountGreaterThan(String value) {
            addCriterion("remittance_amount >", value, "remittanceAmount");
            return (Criteria) this;
        }

        public Criteria andRemittanceAmountGreaterThanOrEqualTo(String value) {
            addCriterion("remittance_amount >=", value, "remittanceAmount");
            return (Criteria) this;
        }

        public Criteria andRemittanceAmountLessThan(String value) {
            addCriterion("remittance_amount <", value, "remittanceAmount");
            return (Criteria) this;
        }

        public Criteria andRemittanceAmountLessThanOrEqualTo(String value) {
            addCriterion("remittance_amount <=", value, "remittanceAmount");
            return (Criteria) this;
        }

        public Criteria andRemittanceAmountLike(String value) {
            addCriterion("remittance_amount like", value, "remittanceAmount");
            return (Criteria) this;
        }

        public Criteria andRemittanceAmountNotLike(String value) {
            addCriterion("remittance_amount not like", value, "remittanceAmount");
            return (Criteria) this;
        }

        public Criteria andRemittanceAmountIn(List<String> values) {
            addCriterion("remittance_amount in", values, "remittanceAmount");
            return (Criteria) this;
        }

        public Criteria andRemittanceAmountNotIn(List<String> values) {
            addCriterion("remittance_amount not in", values, "remittanceAmount");
            return (Criteria) this;
        }

        public Criteria andRemittanceAmountBetween(String value1, String value2) {
            addCriterion("remittance_amount between", value1, value2, "remittanceAmount");
            return (Criteria) this;
        }

        public Criteria andRemittanceAmountNotBetween(String value1, String value2) {
            addCriterion("remittance_amount not between", value1, value2, "remittanceAmount");
            return (Criteria) this;
        }

        public Criteria andReciveNumberIsNull() {
            addCriterion("recive_number is null");
            return (Criteria) this;
        }

        public Criteria andReciveNumberIsNotNull() {
            addCriterion("recive_number is not null");
            return (Criteria) this;
        }

        public Criteria andReciveNumberEqualTo(String value) {
            addCriterion("recive_number =", value, "reciveNumber");
            return (Criteria) this;
        }

        public Criteria andReciveNumberNotEqualTo(String value) {
            addCriterion("recive_number <>", value, "reciveNumber");
            return (Criteria) this;
        }

        public Criteria andReciveNumberGreaterThan(String value) {
            addCriterion("recive_number >", value, "reciveNumber");
            return (Criteria) this;
        }

        public Criteria andReciveNumberGreaterThanOrEqualTo(String value) {
            addCriterion("recive_number >=", value, "reciveNumber");
            return (Criteria) this;
        }

        public Criteria andReciveNumberLessThan(String value) {
            addCriterion("recive_number <", value, "reciveNumber");
            return (Criteria) this;
        }

        public Criteria andReciveNumberLessThanOrEqualTo(String value) {
            addCriterion("recive_number <=", value, "reciveNumber");
            return (Criteria) this;
        }

        public Criteria andReciveNumberLike(String value) {
            addCriterion("recive_number like", value, "reciveNumber");
            return (Criteria) this;
        }

        public Criteria andReciveNumberNotLike(String value) {
            addCriterion("recive_number not like", value, "reciveNumber");
            return (Criteria) this;
        }

        public Criteria andReciveNumberIn(List<String> values) {
            addCriterion("recive_number in", values, "reciveNumber");
            return (Criteria) this;
        }

        public Criteria andReciveNumberNotIn(List<String> values) {
            addCriterion("recive_number not in", values, "reciveNumber");
            return (Criteria) this;
        }

        public Criteria andReciveNumberBetween(String value1, String value2) {
            addCriterion("recive_number between", value1, value2, "reciveNumber");
            return (Criteria) this;
        }

        public Criteria andReciveNumberNotBetween(String value1, String value2) {
            addCriterion("recive_number not between", value1, value2, "reciveNumber");
            return (Criteria) this;
        }

        public Criteria andReciveUserIsNull() {
            addCriterion("recive_user is null");
            return (Criteria) this;
        }

        public Criteria andReciveUserIsNotNull() {
            addCriterion("recive_user is not null");
            return (Criteria) this;
        }

        public Criteria andReciveUserEqualTo(String value) {
            addCriterion("recive_user =", value, "reciveUser");
            return (Criteria) this;
        }

        public Criteria andReciveUserNotEqualTo(String value) {
            addCriterion("recive_user <>", value, "reciveUser");
            return (Criteria) this;
        }

        public Criteria andReciveUserGreaterThan(String value) {
            addCriterion("recive_user >", value, "reciveUser");
            return (Criteria) this;
        }

        public Criteria andReciveUserGreaterThanOrEqualTo(String value) {
            addCriterion("recive_user >=", value, "reciveUser");
            return (Criteria) this;
        }

        public Criteria andReciveUserLessThan(String value) {
            addCriterion("recive_user <", value, "reciveUser");
            return (Criteria) this;
        }

        public Criteria andReciveUserLessThanOrEqualTo(String value) {
            addCriterion("recive_user <=", value, "reciveUser");
            return (Criteria) this;
        }

        public Criteria andReciveUserLike(String value) {
            addCriterion("recive_user like", value, "reciveUser");
            return (Criteria) this;
        }

        public Criteria andReciveUserNotLike(String value) {
            addCriterion("recive_user not like", value, "reciveUser");
            return (Criteria) this;
        }

        public Criteria andReciveUserIn(List<String> values) {
            addCriterion("recive_user in", values, "reciveUser");
            return (Criteria) this;
        }

        public Criteria andReciveUserNotIn(List<String> values) {
            addCriterion("recive_user not in", values, "reciveUser");
            return (Criteria) this;
        }

        public Criteria andReciveUserBetween(String value1, String value2) {
            addCriterion("recive_user between", value1, value2, "reciveUser");
            return (Criteria) this;
        }

        public Criteria andReciveUserNotBetween(String value1, String value2) {
            addCriterion("recive_user not between", value1, value2, "reciveUser");
            return (Criteria) this;
        }

        public Criteria andItemIdIsNull() {
            addCriterion("item_id is null");
            return (Criteria) this;
        }

        public Criteria andItemIdIsNotNull() {
            addCriterion("item_id is not null");
            return (Criteria) this;
        }

        public Criteria andItemIdEqualTo(String value) {
            addCriterion("item_id =", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotEqualTo(String value) {
            addCriterion("item_id <>", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdGreaterThan(String value) {
            addCriterion("item_id >", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdGreaterThanOrEqualTo(String value) {
            addCriterion("item_id >=", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdLessThan(String value) {
            addCriterion("item_id <", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdLessThanOrEqualTo(String value) {
            addCriterion("item_id <=", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdLike(String value) {
            addCriterion("item_id like", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotLike(String value) {
            addCriterion("item_id not like", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdIn(List<String> values) {
            addCriterion("item_id in", values, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotIn(List<String> values) {
            addCriterion("item_id not in", values, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdBetween(String value1, String value2) {
            addCriterion("item_id between", value1, value2, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotBetween(String value1, String value2) {
            addCriterion("item_id not between", value1, value2, "itemId");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("create_user is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("create_user is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("create_user =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("create_user <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("create_user >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("create_user >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("create_user <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("create_user <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("create_user like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("create_user not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("create_user in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("create_user not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("create_user between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("create_user not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andDeletedstatusIsNull() {
            addCriterion("deletedstatus is null");
            return (Criteria) this;
        }

        public Criteria andDeletedstatusIsNotNull() {
            addCriterion("deletedstatus is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedstatusEqualTo(String value) {
            addCriterion("deletedstatus =", value, "deletedstatus");
            return (Criteria) this;
        }

        public Criteria andDeletedstatusNotEqualTo(String value) {
            addCriterion("deletedstatus <>", value, "deletedstatus");
            return (Criteria) this;
        }

        public Criteria andDeletedstatusGreaterThan(String value) {
            addCriterion("deletedstatus >", value, "deletedstatus");
            return (Criteria) this;
        }

        public Criteria andDeletedstatusGreaterThanOrEqualTo(String value) {
            addCriterion("deletedstatus >=", value, "deletedstatus");
            return (Criteria) this;
        }

        public Criteria andDeletedstatusLessThan(String value) {
            addCriterion("deletedstatus <", value, "deletedstatus");
            return (Criteria) this;
        }

        public Criteria andDeletedstatusLessThanOrEqualTo(String value) {
            addCriterion("deletedstatus <=", value, "deletedstatus");
            return (Criteria) this;
        }

        public Criteria andDeletedstatusLike(String value) {
            addCriterion("deletedstatus like", value, "deletedstatus");
            return (Criteria) this;
        }

        public Criteria andDeletedstatusNotLike(String value) {
            addCriterion("deletedstatus not like", value, "deletedstatus");
            return (Criteria) this;
        }

        public Criteria andDeletedstatusIn(List<String> values) {
            addCriterion("deletedstatus in", values, "deletedstatus");
            return (Criteria) this;
        }

        public Criteria andDeletedstatusNotIn(List<String> values) {
            addCriterion("deletedstatus not in", values, "deletedstatus");
            return (Criteria) this;
        }

        public Criteria andDeletedstatusBetween(String value1, String value2) {
            addCriterion("deletedstatus between", value1, value2, "deletedstatus");
            return (Criteria) this;
        }

        public Criteria andDeletedstatusNotBetween(String value1, String value2) {
            addCriterion("deletedstatus not between", value1, value2, "deletedstatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table item_remittance
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table item_remittance
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}