package com.example.demo.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ItemEvaluationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table item_evaluation
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table item_evaluation
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table item_evaluation
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_evaluation
     *
     * @mbg.generated
     */
    public ItemEvaluationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_evaluation
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_evaluation
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_evaluation
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_evaluation
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_evaluation
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_evaluation
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_evaluation
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_evaluation
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_evaluation
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_evaluation
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table item_evaluation
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andItemIdIsNull() {
            addCriterion("item_id is null");
            return (Criteria) this;
        }

        public Criteria andItemIdIsNotNull() {
            addCriterion("item_id is not null");
            return (Criteria) this;
        }

        public Criteria andItemIdEqualTo(String value) {
            addCriterion("item_id =", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotEqualTo(String value) {
            addCriterion("item_id <>", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdGreaterThan(String value) {
            addCriterion("item_id >", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdGreaterThanOrEqualTo(String value) {
            addCriterion("item_id >=", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdLessThan(String value) {
            addCriterion("item_id <", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdLessThanOrEqualTo(String value) {
            addCriterion("item_id <=", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdLike(String value) {
            addCriterion("item_id like", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotLike(String value) {
            addCriterion("item_id not like", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdIn(List<String> values) {
            addCriterion("item_id in", values, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotIn(List<String> values) {
            addCriterion("item_id not in", values, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdBetween(String value1, String value2) {
            addCriterion("item_id between", value1, value2, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotBetween(String value1, String value2) {
            addCriterion("item_id not between", value1, value2, "itemId");
            return (Criteria) this;
        }

        public Criteria andEvaluationSideIsNull() {
            addCriterion("evaluation_side is null");
            return (Criteria) this;
        }

        public Criteria andEvaluationSideIsNotNull() {
            addCriterion("evaluation_side is not null");
            return (Criteria) this;
        }

        public Criteria andEvaluationSideEqualTo(String value) {
            addCriterion("evaluation_side =", value, "evaluationSide");
            return (Criteria) this;
        }

        public Criteria andEvaluationSideNotEqualTo(String value) {
            addCriterion("evaluation_side <>", value, "evaluationSide");
            return (Criteria) this;
        }

        public Criteria andEvaluationSideGreaterThan(String value) {
            addCriterion("evaluation_side >", value, "evaluationSide");
            return (Criteria) this;
        }

        public Criteria andEvaluationSideGreaterThanOrEqualTo(String value) {
            addCriterion("evaluation_side >=", value, "evaluationSide");
            return (Criteria) this;
        }

        public Criteria andEvaluationSideLessThan(String value) {
            addCriterion("evaluation_side <", value, "evaluationSide");
            return (Criteria) this;
        }

        public Criteria andEvaluationSideLessThanOrEqualTo(String value) {
            addCriterion("evaluation_side <=", value, "evaluationSide");
            return (Criteria) this;
        }

        public Criteria andEvaluationSideLike(String value) {
            addCriterion("evaluation_side like", value, "evaluationSide");
            return (Criteria) this;
        }

        public Criteria andEvaluationSideNotLike(String value) {
            addCriterion("evaluation_side not like", value, "evaluationSide");
            return (Criteria) this;
        }

        public Criteria andEvaluationSideIn(List<String> values) {
            addCriterion("evaluation_side in", values, "evaluationSide");
            return (Criteria) this;
        }

        public Criteria andEvaluationSideNotIn(List<String> values) {
            addCriterion("evaluation_side not in", values, "evaluationSide");
            return (Criteria) this;
        }

        public Criteria andEvaluationSideBetween(String value1, String value2) {
            addCriterion("evaluation_side between", value1, value2, "evaluationSide");
            return (Criteria) this;
        }

        public Criteria andEvaluationSideNotBetween(String value1, String value2) {
            addCriterion("evaluation_side not between", value1, value2, "evaluationSide");
            return (Criteria) this;
        }

        public Criteria andEvaluationUserIsNull() {
            addCriterion("evaluation_user is null");
            return (Criteria) this;
        }

        public Criteria andEvaluationUserIsNotNull() {
            addCriterion("evaluation_user is not null");
            return (Criteria) this;
        }

        public Criteria andEvaluationUserEqualTo(String value) {
            addCriterion("evaluation_user =", value, "evaluationUser");
            return (Criteria) this;
        }

        public Criteria andEvaluationUserNotEqualTo(String value) {
            addCriterion("evaluation_user <>", value, "evaluationUser");
            return (Criteria) this;
        }

        public Criteria andEvaluationUserGreaterThan(String value) {
            addCriterion("evaluation_user >", value, "evaluationUser");
            return (Criteria) this;
        }

        public Criteria andEvaluationUserGreaterThanOrEqualTo(String value) {
            addCriterion("evaluation_user >=", value, "evaluationUser");
            return (Criteria) this;
        }

        public Criteria andEvaluationUserLessThan(String value) {
            addCriterion("evaluation_user <", value, "evaluationUser");
            return (Criteria) this;
        }

        public Criteria andEvaluationUserLessThanOrEqualTo(String value) {
            addCriterion("evaluation_user <=", value, "evaluationUser");
            return (Criteria) this;
        }

        public Criteria andEvaluationUserLike(String value) {
            addCriterion("evaluation_user like", value, "evaluationUser");
            return (Criteria) this;
        }

        public Criteria andEvaluationUserNotLike(String value) {
            addCriterion("evaluation_user not like", value, "evaluationUser");
            return (Criteria) this;
        }

        public Criteria andEvaluationUserIn(List<String> values) {
            addCriterion("evaluation_user in", values, "evaluationUser");
            return (Criteria) this;
        }

        public Criteria andEvaluationUserNotIn(List<String> values) {
            addCriterion("evaluation_user not in", values, "evaluationUser");
            return (Criteria) this;
        }

        public Criteria andEvaluationUserBetween(String value1, String value2) {
            addCriterion("evaluation_user between", value1, value2, "evaluationUser");
            return (Criteria) this;
        }

        public Criteria andEvaluationUserNotBetween(String value1, String value2) {
            addCriterion("evaluation_user not between", value1, value2, "evaluationUser");
            return (Criteria) this;
        }

        public Criteria andEvaluationMethodIsNull() {
            addCriterion("evaluation_method is null");
            return (Criteria) this;
        }

        public Criteria andEvaluationMethodIsNotNull() {
            addCriterion("evaluation_method is not null");
            return (Criteria) this;
        }

        public Criteria andEvaluationMethodEqualTo(String value) {
            addCriterion("evaluation_method =", value, "evaluationMethod");
            return (Criteria) this;
        }

        public Criteria andEvaluationMethodNotEqualTo(String value) {
            addCriterion("evaluation_method <>", value, "evaluationMethod");
            return (Criteria) this;
        }

        public Criteria andEvaluationMethodGreaterThan(String value) {
            addCriterion("evaluation_method >", value, "evaluationMethod");
            return (Criteria) this;
        }

        public Criteria andEvaluationMethodGreaterThanOrEqualTo(String value) {
            addCriterion("evaluation_method >=", value, "evaluationMethod");
            return (Criteria) this;
        }

        public Criteria andEvaluationMethodLessThan(String value) {
            addCriterion("evaluation_method <", value, "evaluationMethod");
            return (Criteria) this;
        }

        public Criteria andEvaluationMethodLessThanOrEqualTo(String value) {
            addCriterion("evaluation_method <=", value, "evaluationMethod");
            return (Criteria) this;
        }

        public Criteria andEvaluationMethodLike(String value) {
            addCriterion("evaluation_method like", value, "evaluationMethod");
            return (Criteria) this;
        }

        public Criteria andEvaluationMethodNotLike(String value) {
            addCriterion("evaluation_method not like", value, "evaluationMethod");
            return (Criteria) this;
        }

        public Criteria andEvaluationMethodIn(List<String> values) {
            addCriterion("evaluation_method in", values, "evaluationMethod");
            return (Criteria) this;
        }

        public Criteria andEvaluationMethodNotIn(List<String> values) {
            addCriterion("evaluation_method not in", values, "evaluationMethod");
            return (Criteria) this;
        }

        public Criteria andEvaluationMethodBetween(String value1, String value2) {
            addCriterion("evaluation_method between", value1, value2, "evaluationMethod");
            return (Criteria) this;
        }

        public Criteria andEvaluationMethodNotBetween(String value1, String value2) {
            addCriterion("evaluation_method not between", value1, value2, "evaluationMethod");
            return (Criteria) this;
        }

        public Criteria andEvaluationValueIsNull() {
            addCriterion("evaluation_value is null");
            return (Criteria) this;
        }

        public Criteria andEvaluationValueIsNotNull() {
            addCriterion("evaluation_value is not null");
            return (Criteria) this;
        }

        public Criteria andEvaluationValueEqualTo(String value) {
            addCriterion("evaluation_value =", value, "evaluationValue");
            return (Criteria) this;
        }

        public Criteria andEvaluationValueNotEqualTo(String value) {
            addCriterion("evaluation_value <>", value, "evaluationValue");
            return (Criteria) this;
        }

        public Criteria andEvaluationValueGreaterThan(String value) {
            addCriterion("evaluation_value >", value, "evaluationValue");
            return (Criteria) this;
        }

        public Criteria andEvaluationValueGreaterThanOrEqualTo(String value) {
            addCriterion("evaluation_value >=", value, "evaluationValue");
            return (Criteria) this;
        }

        public Criteria andEvaluationValueLessThan(String value) {
            addCriterion("evaluation_value <", value, "evaluationValue");
            return (Criteria) this;
        }

        public Criteria andEvaluationValueLessThanOrEqualTo(String value) {
            addCriterion("evaluation_value <=", value, "evaluationValue");
            return (Criteria) this;
        }

        public Criteria andEvaluationValueLike(String value) {
            addCriterion("evaluation_value like", value, "evaluationValue");
            return (Criteria) this;
        }

        public Criteria andEvaluationValueNotLike(String value) {
            addCriterion("evaluation_value not like", value, "evaluationValue");
            return (Criteria) this;
        }

        public Criteria andEvaluationValueIn(List<String> values) {
            addCriterion("evaluation_value in", values, "evaluationValue");
            return (Criteria) this;
        }

        public Criteria andEvaluationValueNotIn(List<String> values) {
            addCriterion("evaluation_value not in", values, "evaluationValue");
            return (Criteria) this;
        }

        public Criteria andEvaluationValueBetween(String value1, String value2) {
            addCriterion("evaluation_value between", value1, value2, "evaluationValue");
            return (Criteria) this;
        }

        public Criteria andEvaluationValueNotBetween(String value1, String value2) {
            addCriterion("evaluation_value not between", value1, value2, "evaluationValue");
            return (Criteria) this;
        }

        public Criteria andNoteIsNull() {
            addCriterion("note is null");
            return (Criteria) this;
        }

        public Criteria andNoteIsNotNull() {
            addCriterion("note is not null");
            return (Criteria) this;
        }

        public Criteria andNoteEqualTo(String value) {
            addCriterion("note =", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotEqualTo(String value) {
            addCriterion("note <>", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteGreaterThan(String value) {
            addCriterion("note >", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteGreaterThanOrEqualTo(String value) {
            addCriterion("note >=", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLessThan(String value) {
            addCriterion("note <", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLessThanOrEqualTo(String value) {
            addCriterion("note <=", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLike(String value) {
            addCriterion("note like", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotLike(String value) {
            addCriterion("note not like", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteIn(List<String> values) {
            addCriterion("note in", values, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotIn(List<String> values) {
            addCriterion("note not in", values, "note");
            return (Criteria) this;
        }

        public Criteria andNoteBetween(String value1, String value2) {
            addCriterion("note between", value1, value2, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotBetween(String value1, String value2) {
            addCriterion("note not between", value1, value2, "note");
            return (Criteria) this;
        }

        public Criteria andDeletedstatusIsNull() {
            addCriterion("deletedstatus is null");
            return (Criteria) this;
        }

        public Criteria andDeletedstatusIsNotNull() {
            addCriterion("deletedstatus is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedstatusEqualTo(String value) {
            addCriterion("deletedstatus =", value, "deletedstatus");
            return (Criteria) this;
        }

        public Criteria andDeletedstatusNotEqualTo(String value) {
            addCriterion("deletedstatus <>", value, "deletedstatus");
            return (Criteria) this;
        }

        public Criteria andDeletedstatusGreaterThan(String value) {
            addCriterion("deletedstatus >", value, "deletedstatus");
            return (Criteria) this;
        }

        public Criteria andDeletedstatusGreaterThanOrEqualTo(String value) {
            addCriterion("deletedstatus >=", value, "deletedstatus");
            return (Criteria) this;
        }

        public Criteria andDeletedstatusLessThan(String value) {
            addCriterion("deletedstatus <", value, "deletedstatus");
            return (Criteria) this;
        }

        public Criteria andDeletedstatusLessThanOrEqualTo(String value) {
            addCriterion("deletedstatus <=", value, "deletedstatus");
            return (Criteria) this;
        }

        public Criteria andDeletedstatusLike(String value) {
            addCriterion("deletedstatus like", value, "deletedstatus");
            return (Criteria) this;
        }

        public Criteria andDeletedstatusNotLike(String value) {
            addCriterion("deletedstatus not like", value, "deletedstatus");
            return (Criteria) this;
        }

        public Criteria andDeletedstatusIn(List<String> values) {
            addCriterion("deletedstatus in", values, "deletedstatus");
            return (Criteria) this;
        }

        public Criteria andDeletedstatusNotIn(List<String> values) {
            addCriterion("deletedstatus not in", values, "deletedstatus");
            return (Criteria) this;
        }

        public Criteria andDeletedstatusBetween(String value1, String value2) {
            addCriterion("deletedstatus between", value1, value2, "deletedstatus");
            return (Criteria) this;
        }

        public Criteria andDeletedstatusNotBetween(String value1, String value2) {
            addCriterion("deletedstatus not between", value1, value2, "deletedstatus");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterionForJDBCDate("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterionForJDBCDate("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterionForJDBCDate("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterionForJDBCDate("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("create_user is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("create_user is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("create_user =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("create_user <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("create_user >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("create_user >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("create_user <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("create_user <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("create_user like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("create_user not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("create_user in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("create_user not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("create_user between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("create_user not between", value1, value2, "createUser");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table item_evaluation
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table item_evaluation
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}