package com.example.demo.bean;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table major_issues
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class MajorIssues {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_issues.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * Database Column Remarks:
     *   重大事项类型 1,基金 2,客户
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_issues.type
     *
     * @mbg.generated
     */
    private Byte type;

    /**
     * Database Column Remarks:
     *   关联id 
     *   type=1 基金id 
     *   type=2 客户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_issues.relevance_id
     *
     * @mbg.generated
     */
    private String relevanceId;

    /**
     * Database Column Remarks:
     *   名称 type=1 基金名称 type=2 客户名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_issues.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   事项内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_issues.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_issues.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     * Database Column Remarks:
     *   删除标记： 1未删除； 0 已删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_issues.deletestatus
     *
     * @mbg.generated
     */
    private Integer deletestatus;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major_issues.update_date
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_issues.id
     *
     * @return the value of major_issues.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_issues.id
     *
     * @param id the value for major_issues.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_issues.type
     *
     * @return the value of major_issues.type
     *
     * @mbg.generated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_issues.type
     *
     * @param type the value for major_issues.type
     *
     * @mbg.generated
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_issues.relevance_id
     *
     * @return the value of major_issues.relevance_id
     *
     * @mbg.generated
     */
    public String getRelevanceId() {
        return relevanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_issues.relevance_id
     *
     * @param relevanceId the value for major_issues.relevance_id
     *
     * @mbg.generated
     */
    public void setRelevanceId(String relevanceId) {
        this.relevanceId = relevanceId == null ? null : relevanceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_issues.name
     *
     * @return the value of major_issues.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_issues.name
     *
     * @param name the value for major_issues.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_issues.content
     *
     * @return the value of major_issues.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_issues.content
     *
     * @param content the value for major_issues.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_issues.create_date
     *
     * @return the value of major_issues.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_issues.create_date
     *
     * @param createDate the value for major_issues.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_issues.deletestatus
     *
     * @return the value of major_issues.deletestatus
     *
     * @mbg.generated
     */
    public Integer getDeletestatus() {
        return deletestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_issues.deletestatus
     *
     * @param deletestatus the value for major_issues.deletestatus
     *
     * @mbg.generated
     */
    public void setDeletestatus(Integer deletestatus) {
        this.deletestatus = deletestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major_issues.update_date
     *
     * @return the value of major_issues.update_date
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major_issues.update_date
     *
     * @param updateDate the value for major_issues.update_date
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}