package com.example.demo.bean;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table message_remind
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class MessageRemind {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_remind.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   数据的id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_remind.data_id
     *
     * @mbg.generated
     */
    private String dataId;

    /**
     * Database Column Remarks:
     *   数据类型1项目 2基金
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_remind.data_type
     *
     * @mbg.generated
     */
    private String dataType;

    /**
     * Database Column Remarks:
     *   员工编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_remind.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     * Database Column Remarks:
     *   提醒是否被看，0位已被看，1未被看
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_remind.is_read
     *
     * @mbg.generated
     */
    private Integer isRead;

    /**
     * Database Column Remarks:
     *   删除标记 1未删，0已删
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_remind.deleted_status
     *
     * @mbg.generated
     */
    private String deletedStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_remind.id
     *
     * @return the value of message_remind.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_remind.id
     *
     * @param id the value for message_remind.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_remind.data_id
     *
     * @return the value of message_remind.data_id
     *
     * @mbg.generated
     */
    public String getDataId() {
        return dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_remind.data_id
     *
     * @param dataId the value for message_remind.data_id
     *
     * @mbg.generated
     */
    public void setDataId(String dataId) {
        this.dataId = dataId == null ? null : dataId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_remind.data_type
     *
     * @return the value of message_remind.data_type
     *
     * @mbg.generated
     */
    public String getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_remind.data_type
     *
     * @param dataType the value for message_remind.data_type
     *
     * @mbg.generated
     */
    public void setDataType(String dataType) {
        this.dataType = dataType == null ? null : dataType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_remind.user_id
     *
     * @return the value of message_remind.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_remind.user_id
     *
     * @param userId the value for message_remind.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_remind.is_read
     *
     * @return the value of message_remind.is_read
     *
     * @mbg.generated
     */
    public Integer getIsRead() {
        return isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_remind.is_read
     *
     * @param isRead the value for message_remind.is_read
     *
     * @mbg.generated
     */
    public void setIsRead(Integer isRead) {
        this.isRead = isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_remind.deleted_status
     *
     * @return the value of message_remind.deleted_status
     *
     * @mbg.generated
     */
    public String getDeletedStatus() {
        return deletedStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_remind.deleted_status
     *
     * @param deletedStatus the value for message_remind.deleted_status
     *
     * @mbg.generated
     */
    public void setDeletedStatus(String deletedStatus) {
        this.deletedStatus = deletedStatus == null ? null : deletedStatus.trim();
    }
}