package com.example.demo.bean;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table quasiinvestment
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Quasiinvestment {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quasiinvestment.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * Database Column Remarks:
     *   项目id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quasiinvestment.item_id
     *
     * @mbg.generated
     */
    private String itemId;

    /**
     * Database Column Remarks:
     *   首次接触时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quasiinvestment.first_contact
     *
     * @mbg.generated
     */
    private Date firstContact;

    /**
     * Database Column Remarks:
     *   最近更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quasiinvestment.last_update
     *
     * @mbg.generated
     */
    private Date lastUpdate;

    /**
     * Database Column Remarks:
     *   项目来源（挖掘人）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quasiinvestment.item_source
     *
     * @mbg.generated
     */
    private String itemSource;

    /**
     * Database Column Remarks:
     *   项目地区
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quasiinvestment.item_area
     *
     * @mbg.generated
     */
    private String itemArea;

    /**
     * Database Column Remarks:
     *   计划募资金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quasiinvestment.plan_prospectus
     *
     * @mbg.generated
     */
    private String planProspectus;

    /**
     * Database Column Remarks:
     *   本轮估值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quasiinvestment.current_valuation
     *
     * @mbg.generated
     */
    private String currentValuation;

    /**
     * Database Column Remarks:
     *   我司拟投资金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quasiinvestment.Own_investment
     *
     * @mbg.generated
     */
    private String ownInvestment;

    /**
     * Database Column Remarks:
     *   计划打款时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quasiinvestment.Planplay_time
     *
     * @mbg.generated
     */
    private Date planplayTime;

    /**
     * Database Column Remarks:
     *   跟进状态 550 初步接触 551 深入跟进 552 暂时搁置 553 终止跟进 5554其他
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quasiinvestment.Followup_status
     *
     * @mbg.generated
     */
    private String followupStatus;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quasiinvestment.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     * Database Column Remarks:
     *   创建人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quasiinvestment.create_user
     *
     * @mbg.generated
     */
    private String createUser;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quasiinvestment.update_date
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     * Database Column Remarks:
     *   删除标志
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quasiinvestment.deteledstatus
     *
     * @mbg.generated
     */
    private Integer deteledstatus;

    /**
     * Database Column Remarks:
     *   创始人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quasiinvestment.createUser
     *
     * @mbg.generated
     */
    private String createuser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quasiinvestment.id
     *
     * @return the value of quasiinvestment.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quasiinvestment.id
     *
     * @param id the value for quasiinvestment.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quasiinvestment.item_id
     *
     * @return the value of quasiinvestment.item_id
     *
     * @mbg.generated
     */
    public String getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quasiinvestment.item_id
     *
     * @param itemId the value for quasiinvestment.item_id
     *
     * @mbg.generated
     */
    public void setItemId(String itemId) {
        this.itemId = itemId == null ? null : itemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quasiinvestment.first_contact
     *
     * @return the value of quasiinvestment.first_contact
     *
     * @mbg.generated
     */
    public Date getFirstContact() {
        return firstContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quasiinvestment.first_contact
     *
     * @param firstContact the value for quasiinvestment.first_contact
     *
     * @mbg.generated
     */
    public void setFirstContact(Date firstContact) {
        this.firstContact = firstContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quasiinvestment.last_update
     *
     * @return the value of quasiinvestment.last_update
     *
     * @mbg.generated
     */
    public Date getLastUpdate() {
        return lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quasiinvestment.last_update
     *
     * @param lastUpdate the value for quasiinvestment.last_update
     *
     * @mbg.generated
     */
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quasiinvestment.item_source
     *
     * @return the value of quasiinvestment.item_source
     *
     * @mbg.generated
     */
    public String getItemSource() {
        return itemSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quasiinvestment.item_source
     *
     * @param itemSource the value for quasiinvestment.item_source
     *
     * @mbg.generated
     */
    public void setItemSource(String itemSource) {
        this.itemSource = itemSource == null ? null : itemSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quasiinvestment.item_area
     *
     * @return the value of quasiinvestment.item_area
     *
     * @mbg.generated
     */
    public String getItemArea() {
        return itemArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quasiinvestment.item_area
     *
     * @param itemArea the value for quasiinvestment.item_area
     *
     * @mbg.generated
     */
    public void setItemArea(String itemArea) {
        this.itemArea = itemArea == null ? null : itemArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quasiinvestment.plan_prospectus
     *
     * @return the value of quasiinvestment.plan_prospectus
     *
     * @mbg.generated
     */
    public String getPlanProspectus() {
        return planProspectus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quasiinvestment.plan_prospectus
     *
     * @param planProspectus the value for quasiinvestment.plan_prospectus
     *
     * @mbg.generated
     */
    public void setPlanProspectus(String planProspectus) {
        this.planProspectus = planProspectus == null ? null : planProspectus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quasiinvestment.current_valuation
     *
     * @return the value of quasiinvestment.current_valuation
     *
     * @mbg.generated
     */
    public String getCurrentValuation() {
        return currentValuation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quasiinvestment.current_valuation
     *
     * @param currentValuation the value for quasiinvestment.current_valuation
     *
     * @mbg.generated
     */
    public void setCurrentValuation(String currentValuation) {
        this.currentValuation = currentValuation == null ? null : currentValuation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quasiinvestment.Own_investment
     *
     * @return the value of quasiinvestment.Own_investment
     *
     * @mbg.generated
     */
    public String getOwnInvestment() {
        return ownInvestment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quasiinvestment.Own_investment
     *
     * @param ownInvestment the value for quasiinvestment.Own_investment
     *
     * @mbg.generated
     */
    public void setOwnInvestment(String ownInvestment) {
        this.ownInvestment = ownInvestment == null ? null : ownInvestment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quasiinvestment.Planplay_time
     *
     * @return the value of quasiinvestment.Planplay_time
     *
     * @mbg.generated
     */
    public Date getPlanplayTime() {
        return planplayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quasiinvestment.Planplay_time
     *
     * @param planplayTime the value for quasiinvestment.Planplay_time
     *
     * @mbg.generated
     */
    public void setPlanplayTime(Date planplayTime) {
        this.planplayTime = planplayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quasiinvestment.Followup_status
     *
     * @return the value of quasiinvestment.Followup_status
     *
     * @mbg.generated
     */
    public String getFollowupStatus() {
        return followupStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quasiinvestment.Followup_status
     *
     * @param followupStatus the value for quasiinvestment.Followup_status
     *
     * @mbg.generated
     */
    public void setFollowupStatus(String followupStatus) {
        this.followupStatus = followupStatus == null ? null : followupStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quasiinvestment.create_date
     *
     * @return the value of quasiinvestment.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quasiinvestment.create_date
     *
     * @param createDate the value for quasiinvestment.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quasiinvestment.create_user
     *
     * @return the value of quasiinvestment.create_user
     *
     * @mbg.generated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quasiinvestment.create_user
     *
     * @param createUser the value for quasiinvestment.create_user
     *
     * @mbg.generated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quasiinvestment.update_date
     *
     * @return the value of quasiinvestment.update_date
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quasiinvestment.update_date
     *
     * @param updateDate the value for quasiinvestment.update_date
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quasiinvestment.deteledstatus
     *
     * @return the value of quasiinvestment.deteledstatus
     *
     * @mbg.generated
     */
    public Integer getDeteledstatus() {
        return deteledstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quasiinvestment.deteledstatus
     *
     * @param deteledstatus the value for quasiinvestment.deteledstatus
     *
     * @mbg.generated
     */
    public void setDeteledstatus(Integer deteledstatus) {
        this.deteledstatus = deteledstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quasiinvestment.createUser
     *
     * @return the value of quasiinvestment.createUser
     *
     * @mbg.generated
     */
    public String getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quasiinvestment.createUser
     *
     * @param createuser the value for quasiinvestment.createUser
     *
     * @mbg.generated
     */
    public void setCreateuser(String createuser) {
        this.createuser = createuser == null ? null : createuser.trim();
    }
}