package com.example.demo.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ScheduleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table schedule
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table schedule
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table schedule
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbg.generated
     */
    public ScheduleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table schedule
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andScheduleDateIsNull() {
            addCriterion("schedule_date is null");
            return (Criteria) this;
        }

        public Criteria andScheduleDateIsNotNull() {
            addCriterion("schedule_date is not null");
            return (Criteria) this;
        }

        public Criteria andScheduleDateEqualTo(Date value) {
            addCriterion("schedule_date =", value, "scheduleDate");
            return (Criteria) this;
        }

        public Criteria andScheduleDateNotEqualTo(Date value) {
            addCriterion("schedule_date <>", value, "scheduleDate");
            return (Criteria) this;
        }

        public Criteria andScheduleDateGreaterThan(Date value) {
            addCriterion("schedule_date >", value, "scheduleDate");
            return (Criteria) this;
        }

        public Criteria andScheduleDateGreaterThanOrEqualTo(Date value) {
            addCriterion("schedule_date >=", value, "scheduleDate");
            return (Criteria) this;
        }

        public Criteria andScheduleDateLessThan(Date value) {
            addCriterion("schedule_date <", value, "scheduleDate");
            return (Criteria) this;
        }

        public Criteria andScheduleDateLessThanOrEqualTo(Date value) {
            addCriterion("schedule_date <=", value, "scheduleDate");
            return (Criteria) this;
        }

        public Criteria andScheduleDateIn(List<Date> values) {
            addCriterion("schedule_date in", values, "scheduleDate");
            return (Criteria) this;
        }

        public Criteria andScheduleDateNotIn(List<Date> values) {
            addCriterion("schedule_date not in", values, "scheduleDate");
            return (Criteria) this;
        }

        public Criteria andScheduleDateBetween(Date value1, Date value2) {
            addCriterion("schedule_date between", value1, value2, "scheduleDate");
            return (Criteria) this;
        }

        public Criteria andScheduleDateNotBetween(Date value1, Date value2) {
            addCriterion("schedule_date not between", value1, value2, "scheduleDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("update_date is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("update_date is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("update_date =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("update_date <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("update_date >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("update_date >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("update_date <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("update_date <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("update_date in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("update_date not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("update_date between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("update_date not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andDeteledstatusIsNull() {
            addCriterion("deteledstatus is null");
            return (Criteria) this;
        }

        public Criteria andDeteledstatusIsNotNull() {
            addCriterion("deteledstatus is not null");
            return (Criteria) this;
        }

        public Criteria andDeteledstatusEqualTo(Integer value) {
            addCriterion("deteledstatus =", value, "deteledstatus");
            return (Criteria) this;
        }

        public Criteria andDeteledstatusNotEqualTo(Integer value) {
            addCriterion("deteledstatus <>", value, "deteledstatus");
            return (Criteria) this;
        }

        public Criteria andDeteledstatusGreaterThan(Integer value) {
            addCriterion("deteledstatus >", value, "deteledstatus");
            return (Criteria) this;
        }

        public Criteria andDeteledstatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("deteledstatus >=", value, "deteledstatus");
            return (Criteria) this;
        }

        public Criteria andDeteledstatusLessThan(Integer value) {
            addCriterion("deteledstatus <", value, "deteledstatus");
            return (Criteria) this;
        }

        public Criteria andDeteledstatusLessThanOrEqualTo(Integer value) {
            addCriterion("deteledstatus <=", value, "deteledstatus");
            return (Criteria) this;
        }

        public Criteria andDeteledstatusIn(List<Integer> values) {
            addCriterion("deteledstatus in", values, "deteledstatus");
            return (Criteria) this;
        }

        public Criteria andDeteledstatusNotIn(List<Integer> values) {
            addCriterion("deteledstatus not in", values, "deteledstatus");
            return (Criteria) this;
        }

        public Criteria andDeteledstatusBetween(Integer value1, Integer value2) {
            addCriterion("deteledstatus between", value1, value2, "deteledstatus");
            return (Criteria) this;
        }

        public Criteria andDeteledstatusNotBetween(Integer value1, Integer value2) {
            addCriterion("deteledstatus not between", value1, value2, "deteledstatus");
            return (Criteria) this;
        }

        public Criteria andExpectedCompleteDayIsNull() {
            addCriterion("expected_complete_day is null");
            return (Criteria) this;
        }

        public Criteria andExpectedCompleteDayIsNotNull() {
            addCriterion("expected_complete_day is not null");
            return (Criteria) this;
        }

        public Criteria andExpectedCompleteDayEqualTo(Integer value) {
            addCriterion("expected_complete_day =", value, "expectedCompleteDay");
            return (Criteria) this;
        }

        public Criteria andExpectedCompleteDayNotEqualTo(Integer value) {
            addCriterion("expected_complete_day <>", value, "expectedCompleteDay");
            return (Criteria) this;
        }

        public Criteria andExpectedCompleteDayGreaterThan(Integer value) {
            addCriterion("expected_complete_day >", value, "expectedCompleteDay");
            return (Criteria) this;
        }

        public Criteria andExpectedCompleteDayGreaterThanOrEqualTo(Integer value) {
            addCriterion("expected_complete_day >=", value, "expectedCompleteDay");
            return (Criteria) this;
        }

        public Criteria andExpectedCompleteDayLessThan(Integer value) {
            addCriterion("expected_complete_day <", value, "expectedCompleteDay");
            return (Criteria) this;
        }

        public Criteria andExpectedCompleteDayLessThanOrEqualTo(Integer value) {
            addCriterion("expected_complete_day <=", value, "expectedCompleteDay");
            return (Criteria) this;
        }

        public Criteria andExpectedCompleteDayIn(List<Integer> values) {
            addCriterion("expected_complete_day in", values, "expectedCompleteDay");
            return (Criteria) this;
        }

        public Criteria andExpectedCompleteDayNotIn(List<Integer> values) {
            addCriterion("expected_complete_day not in", values, "expectedCompleteDay");
            return (Criteria) this;
        }

        public Criteria andExpectedCompleteDayBetween(Integer value1, Integer value2) {
            addCriterion("expected_complete_day between", value1, value2, "expectedCompleteDay");
            return (Criteria) this;
        }

        public Criteria andExpectedCompleteDayNotBetween(Integer value1, Integer value2) {
            addCriterion("expected_complete_day not between", value1, value2, "expectedCompleteDay");
            return (Criteria) this;
        }

        public Criteria andExpectedCompleteDateIsNull() {
            addCriterion("expected_complete_date is null");
            return (Criteria) this;
        }

        public Criteria andExpectedCompleteDateIsNotNull() {
            addCriterion("expected_complete_date is not null");
            return (Criteria) this;
        }

        public Criteria andExpectedCompleteDateEqualTo(Date value) {
            addCriterion("expected_complete_date =", value, "expectedCompleteDate");
            return (Criteria) this;
        }

        public Criteria andExpectedCompleteDateNotEqualTo(Date value) {
            addCriterion("expected_complete_date <>", value, "expectedCompleteDate");
            return (Criteria) this;
        }

        public Criteria andExpectedCompleteDateGreaterThan(Date value) {
            addCriterion("expected_complete_date >", value, "expectedCompleteDate");
            return (Criteria) this;
        }

        public Criteria andExpectedCompleteDateGreaterThanOrEqualTo(Date value) {
            addCriterion("expected_complete_date >=", value, "expectedCompleteDate");
            return (Criteria) this;
        }

        public Criteria andExpectedCompleteDateLessThan(Date value) {
            addCriterion("expected_complete_date <", value, "expectedCompleteDate");
            return (Criteria) this;
        }

        public Criteria andExpectedCompleteDateLessThanOrEqualTo(Date value) {
            addCriterion("expected_complete_date <=", value, "expectedCompleteDate");
            return (Criteria) this;
        }

        public Criteria andExpectedCompleteDateIn(List<Date> values) {
            addCriterion("expected_complete_date in", values, "expectedCompleteDate");
            return (Criteria) this;
        }

        public Criteria andExpectedCompleteDateNotIn(List<Date> values) {
            addCriterion("expected_complete_date not in", values, "expectedCompleteDate");
            return (Criteria) this;
        }

        public Criteria andExpectedCompleteDateBetween(Date value1, Date value2) {
            addCriterion("expected_complete_date between", value1, value2, "expectedCompleteDate");
            return (Criteria) this;
        }

        public Criteria andExpectedCompleteDateNotBetween(Date value1, Date value2) {
            addCriterion("expected_complete_date not between", value1, value2, "expectedCompleteDate");
            return (Criteria) this;
        }

        public Criteria andSignificanceIsNull() {
            addCriterion("significance is null");
            return (Criteria) this;
        }

        public Criteria andSignificanceIsNotNull() {
            addCriterion("significance is not null");
            return (Criteria) this;
        }

        public Criteria andSignificanceEqualTo(Integer value) {
            addCriterion("significance =", value, "significance");
            return (Criteria) this;
        }

        public Criteria andSignificanceNotEqualTo(Integer value) {
            addCriterion("significance <>", value, "significance");
            return (Criteria) this;
        }

        public Criteria andSignificanceGreaterThan(Integer value) {
            addCriterion("significance >", value, "significance");
            return (Criteria) this;
        }

        public Criteria andSignificanceGreaterThanOrEqualTo(Integer value) {
            addCriterion("significance >=", value, "significance");
            return (Criteria) this;
        }

        public Criteria andSignificanceLessThan(Integer value) {
            addCriterion("significance <", value, "significance");
            return (Criteria) this;
        }

        public Criteria andSignificanceLessThanOrEqualTo(Integer value) {
            addCriterion("significance <=", value, "significance");
            return (Criteria) this;
        }

        public Criteria andSignificanceIn(List<Integer> values) {
            addCriterion("significance in", values, "significance");
            return (Criteria) this;
        }

        public Criteria andSignificanceNotIn(List<Integer> values) {
            addCriterion("significance not in", values, "significance");
            return (Criteria) this;
        }

        public Criteria andSignificanceBetween(Integer value1, Integer value2) {
            addCriterion("significance between", value1, value2, "significance");
            return (Criteria) this;
        }

        public Criteria andSignificanceNotBetween(Integer value1, Integer value2) {
            addCriterion("significance not between", value1, value2, "significance");
            return (Criteria) this;
        }

        public Criteria andRepetitionperiodIsNull() {
            addCriterion("repetitionPeriod is null");
            return (Criteria) this;
        }

        public Criteria andRepetitionperiodIsNotNull() {
            addCriterion("repetitionPeriod is not null");
            return (Criteria) this;
        }

        public Criteria andRepetitionperiodEqualTo(Integer value) {
            addCriterion("repetitionPeriod =", value, "repetitionperiod");
            return (Criteria) this;
        }

        public Criteria andRepetitionperiodNotEqualTo(Integer value) {
            addCriterion("repetitionPeriod <>", value, "repetitionperiod");
            return (Criteria) this;
        }

        public Criteria andRepetitionperiodGreaterThan(Integer value) {
            addCriterion("repetitionPeriod >", value, "repetitionperiod");
            return (Criteria) this;
        }

        public Criteria andRepetitionperiodGreaterThanOrEqualTo(Integer value) {
            addCriterion("repetitionPeriod >=", value, "repetitionperiod");
            return (Criteria) this;
        }

        public Criteria andRepetitionperiodLessThan(Integer value) {
            addCriterion("repetitionPeriod <", value, "repetitionperiod");
            return (Criteria) this;
        }

        public Criteria andRepetitionperiodLessThanOrEqualTo(Integer value) {
            addCriterion("repetitionPeriod <=", value, "repetitionperiod");
            return (Criteria) this;
        }

        public Criteria andRepetitionperiodIn(List<Integer> values) {
            addCriterion("repetitionPeriod in", values, "repetitionperiod");
            return (Criteria) this;
        }

        public Criteria andRepetitionperiodNotIn(List<Integer> values) {
            addCriterion("repetitionPeriod not in", values, "repetitionperiod");
            return (Criteria) this;
        }

        public Criteria andRepetitionperiodBetween(Integer value1, Integer value2) {
            addCriterion("repetitionPeriod between", value1, value2, "repetitionperiod");
            return (Criteria) this;
        }

        public Criteria andRepetitionperiodNotBetween(Integer value1, Integer value2) {
            addCriterion("repetitionPeriod not between", value1, value2, "repetitionperiod");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("create_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("create_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(String value) {
            addCriterion("create_user_id =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(String value) {
            addCriterion("create_user_id <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(String value) {
            addCriterion("create_user_id >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("create_user_id >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(String value) {
            addCriterion("create_user_id <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(String value) {
            addCriterion("create_user_id <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLike(String value) {
            addCriterion("create_user_id like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotLike(String value) {
            addCriterion("create_user_id not like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<String> values) {
            addCriterion("create_user_id in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<String> values) {
            addCriterion("create_user_id not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(String value1, String value2) {
            addCriterion("create_user_id between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(String value1, String value2) {
            addCriterion("create_user_id not between", value1, value2, "createUserId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table schedule
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table schedule
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}