package com.example.demo.dao;

import com.example.demo.bean.FundDistribution;
import com.example.demo.bean.FundDistributionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FundDistributionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_distribution
     *
     * @mbg.generated
     */
    long countByExample(FundDistributionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_distribution
     *
     * @mbg.generated
     */
    int deleteByExample(FundDistributionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_distribution
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_distribution
     *
     * @mbg.generated
     */
    int insert(FundDistribution record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_distribution
     *
     * @mbg.generated
     */
    int insertSelective(FundDistribution record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_distribution
     *
     * @mbg.generated
     */
    List<FundDistribution> selectByExample(FundDistributionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_distribution
     *
     * @mbg.generated
     */
    FundDistribution selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_distribution
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FundDistribution record, @Param("example") FundDistributionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_distribution
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FundDistribution record, @Param("example") FundDistributionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_distribution
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FundDistribution record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_distribution
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FundDistribution record);
}