package com.example.demo.dao;

import com.example.demo.bean.InvestmentDirectionFundRel;
import com.example.demo.bean.InvestmentDirectionFundRelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InvestmentDirectionFundRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table investment_direction_fund_rel
     *
     * @mbg.generated
     */
    long countByExample(InvestmentDirectionFundRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table investment_direction_fund_rel
     *
     * @mbg.generated
     */
    int deleteByExample(InvestmentDirectionFundRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table investment_direction_fund_rel
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table investment_direction_fund_rel
     *
     * @mbg.generated
     */
    int insert(InvestmentDirectionFundRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table investment_direction_fund_rel
     *
     * @mbg.generated
     */
    int insertSelective(InvestmentDirectionFundRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table investment_direction_fund_rel
     *
     * @mbg.generated
     */
    List<InvestmentDirectionFundRel> selectByExample(InvestmentDirectionFundRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table investment_direction_fund_rel
     *
     * @mbg.generated
     */
    InvestmentDirectionFundRel selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table investment_direction_fund_rel
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") InvestmentDirectionFundRel record, @Param("example") InvestmentDirectionFundRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table investment_direction_fund_rel
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") InvestmentDirectionFundRel record, @Param("example") InvestmentDirectionFundRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table investment_direction_fund_rel
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(InvestmentDirectionFundRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table investment_direction_fund_rel
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(InvestmentDirectionFundRel record);
}