package com.example.demo.dao;

import com.example.demo.bean.ItemVote;
import com.example.demo.bean.ItemVoteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ItemVoteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_vote
     *
     * @mbg.generated
     */
    long countByExample(ItemVoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_vote
     *
     * @mbg.generated
     */
    int deleteByExample(ItemVoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_vote
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_vote
     *
     * @mbg.generated
     */
    int insert(ItemVote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_vote
     *
     * @mbg.generated
     */
    int insertSelective(ItemVote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_vote
     *
     * @mbg.generated
     */
    List<ItemVote> selectByExample(ItemVoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_vote
     *
     * @mbg.generated
     */
    ItemVote selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_vote
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ItemVote record, @Param("example") ItemVoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_vote
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ItemVote record, @Param("example") ItemVoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_vote
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ItemVote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_vote
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ItemVote record);
}