package com.example.demo.dao;

import com.example.demo.bean.ItemRelatedUser;
import com.example.demo.bean.ItemRelatedUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ItemRelatedUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_related_user
     *
     * @mbg.generated
     */
    long countByExample(ItemRelatedUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_related_user
     *
     * @mbg.generated
     */
    int deleteByExample(ItemRelatedUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_related_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_related_user
     *
     * @mbg.generated
     */
    int insert(ItemRelatedUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_related_user
     *
     * @mbg.generated
     */
    int insertSelective(ItemRelatedUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_related_user
     *
     * @mbg.generated
     */
    List<ItemRelatedUser> selectByExample(ItemRelatedUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_related_user
     *
     * @mbg.generated
     */
    ItemRelatedUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_related_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ItemRelatedUser record, @Param("example") ItemRelatedUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_related_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ItemRelatedUser record, @Param("example") ItemRelatedUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_related_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ItemRelatedUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_related_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ItemRelatedUser record);
}