package com.example.demo.dao;

import com.example.demo.bean.Loginlog;
import com.example.demo.bean.LoginlogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LoginlogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOGINLOG
     *
     * @mbg.generated
     */
    long countByExample(LoginlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOGINLOG
     *
     * @mbg.generated
     */
    int deleteByExample(LoginlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOGINLOG
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOGINLOG
     *
     * @mbg.generated
     */
    int insert(Loginlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOGINLOG
     *
     * @mbg.generated
     */
    int insertSelective(Loginlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOGINLOG
     *
     * @mbg.generated
     */
    List<Loginlog> selectByExample(LoginlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOGINLOG
     *
     * @mbg.generated
     */
    Loginlog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOGINLOG
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Loginlog record, @Param("example") LoginlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOGINLOG
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Loginlog record, @Param("example") LoginlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOGINLOG
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Loginlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOGINLOG
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Loginlog record);
}