package com.example.demo.dao;

import com.example.demo.bean.QuasiinvestmentFundRel;
import com.example.demo.bean.QuasiinvestmentFundRelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QuasiinvestmentFundRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quasiinvestment_fund_rel
     *
     * @mbg.generated
     */
    long countByExample(QuasiinvestmentFundRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quasiinvestment_fund_rel
     *
     * @mbg.generated
     */
    int deleteByExample(QuasiinvestmentFundRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quasiinvestment_fund_rel
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quasiinvestment_fund_rel
     *
     * @mbg.generated
     */
    int insert(QuasiinvestmentFundRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quasiinvestment_fund_rel
     *
     * @mbg.generated
     */
    int insertSelective(QuasiinvestmentFundRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quasiinvestment_fund_rel
     *
     * @mbg.generated
     */
    List<QuasiinvestmentFundRel> selectByExample(QuasiinvestmentFundRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quasiinvestment_fund_rel
     *
     * @mbg.generated
     */
    QuasiinvestmentFundRel selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quasiinvestment_fund_rel
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") QuasiinvestmentFundRel record, @Param("example") QuasiinvestmentFundRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quasiinvestment_fund_rel
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") QuasiinvestmentFundRel record, @Param("example") QuasiinvestmentFundRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quasiinvestment_fund_rel
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(QuasiinvestmentFundRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quasiinvestment_fund_rel
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(QuasiinvestmentFundRel record);
}