package com.example.demo.dao;

import com.example.demo.bean.RoleItemRel;
import com.example.demo.bean.RoleItemRelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleItemRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_item_rel
     *
     * @mbg.generated
     */
    long countByExample(RoleItemRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_item_rel
     *
     * @mbg.generated
     */
    int deleteByExample(RoleItemRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_item_rel
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_item_rel
     *
     * @mbg.generated
     */
    int insert(RoleItemRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_item_rel
     *
     * @mbg.generated
     */
    int insertSelective(RoleItemRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_item_rel
     *
     * @mbg.generated
     */
    List<RoleItemRel> selectByExample(RoleItemRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_item_rel
     *
     * @mbg.generated
     */
    RoleItemRel selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_item_rel
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RoleItemRel record, @Param("example") RoleItemRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_item_rel
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RoleItemRel record, @Param("example") RoleItemRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_item_rel
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RoleItemRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_item_rel
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RoleItemRel record);
}