package com.example.demo.dao;

import com.example.demo.bean.TzUserScheduleRel;
import com.example.demo.bean.TzUserScheduleRelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TzUserScheduleRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_user_schedule_rel
     *
     * @mbg.generated
     */
    long countByExample(TzUserScheduleRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_user_schedule_rel
     *
     * @mbg.generated
     */
    int deleteByExample(TzUserScheduleRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_user_schedule_rel
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_user_schedule_rel
     *
     * @mbg.generated
     */
    int insert(TzUserScheduleRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_user_schedule_rel
     *
     * @mbg.generated
     */
    int insertSelective(TzUserScheduleRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_user_schedule_rel
     *
     * @mbg.generated
     */
    List<TzUserScheduleRel> selectByExample(TzUserScheduleRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_user_schedule_rel
     *
     * @mbg.generated
     */
    TzUserScheduleRel selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_user_schedule_rel
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TzUserScheduleRel record, @Param("example") TzUserScheduleRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_user_schedule_rel
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TzUserScheduleRel record, @Param("example") TzUserScheduleRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_user_schedule_rel
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TzUserScheduleRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_user_schedule_rel
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TzUserScheduleRel record);
}